import { Module, Question, Language } from './types';

export const PLACEMENT_QUESTIONS: Record<Language, Question[]> = {
  English: [
    { id: 'p1', type: 'Comprehension', question: 'What is the opposite of "Happy"?', options: ['Sad', 'Angry', 'Excited', 'Bored'], correctAnswer: 'Sad' },
    { id: 'p2', type: 'Comprehension', question: 'Choose the correct sentence:', options: ['He go to school.', 'He goes to school.', 'He going to school.', 'He gone to school.'], correctAnswer: 'He goes to school.' },
    { id: 'p3', type: 'Comprehension', question: 'What does "to break the ice" mean?', options: ['To freeze something', 'To start a conversation', 'To break a window', 'To be very cold'], correctAnswer: 'To start a conversation' },
    { id: 'p3b', type: 'Comprehension', question: 'Which word is a synonym for "Enormous"?', options: ['Tiny', 'Huge', 'Soft', 'Fast'], correctAnswer: 'Huge' },
    { id: 'p3c', type: 'Comprehension', question: 'Identify the verb in this sentence: "The cat slept on the mat."', options: ['Cat', 'Slept', 'On', 'Mat'], correctAnswer: 'Slept' },
  ],
  Malay: [
    { id: 'p4', type: 'Comprehension', question: 'Apakah maksud "Selamat Pagi"?', options: ['Good Night', 'Good Morning', 'Good Afternoon', 'Goodbye'], correctAnswer: 'Good Morning' },
    { id: 'p5', type: 'Comprehension', question: 'Pilih perkataan yang betul: "Saya ___ nasi."', options: ['makan', 'minum', 'tidur', 'lari'], correctAnswer: 'makan' },
    { id: 'p6', type: 'Comprehension', question: 'Apakah maksud peribahasa "Kaki bangku"?', options: ['Seseorang yang suka duduk', 'Seseorang yang tidak pandai bermain bola', 'Seseorang yang rajin', 'Seseorang yang sombong'], correctAnswer: 'Seseorang yang tidak pandai bermain bola' },
    { id: 'p6b', type: 'Comprehension', question: 'Apakah lawan bagi perkataan "Besar"?', options: ['Kecil', 'Tinggi', 'Panjang', 'Lebar'], correctAnswer: 'Kecil' },
    { id: 'p6c', type: 'Comprehension', question: 'Pilih kata ganti nama diri yang betul: "___ sedang membaca buku."', options: ['Dia', 'Itu', 'Sana', 'Sini'], correctAnswer: 'Dia' },
  ],
  Chinese: [
    { id: 'p7', type: 'Comprehension', question: '"你好" 是什么意思？', options: ['Goodbye', 'Hello', 'Thank you', 'Sorry'], correctAnswer: 'Hello' },
    { id: 'p8', type: 'Comprehension', question: '请选择正确的量词：一___书', options: ['个', '只', '本', '件'], correctAnswer: '本' },
    { id: 'p9', type: 'Comprehension', question: '"画龙点睛" 的意思是什么？', options: ['To draw a dragon', 'To add the finishing touch', 'To be very fast', 'To be very strong'], correctAnswer: 'To add the finishing touch' },
    { id: 'p9b', type: 'Comprehension', question: '"苹果" 的拼音是什么？', options: ['Píngguǒ', 'Bānguǒ', 'Míngguǒ', 'Tíngguǒ'], correctAnswer: 'Píngguǒ' },
    { id: 'p9c', type: 'Comprehension', question: '请选择 "大" 的反义词：', options: ['小', '多', '少', '长'], correctAnswer: '小' },
  ],
};

export const MODULES: Module[] = [
  // ==========================================
  // ENGLISH
  // ==========================================
  
  // BEGINNER
  {
    id: 'en-beg-listen',
    language: 'English',
    level: 'Beginner',
    type: 'Listening',
    title: 'Basic Greetings',
    description: 'Listen to common greetings and identify them.',
    questions: [
      { id: 'q1', type: 'Listening', question: 'What did you hear?', options: ['Hello', 'Goodbye', 'Good morning', 'Good night'], correctAnswer: 'Hello', audioText: 'Hello, how are you today?' },
      { id: 'q1b', type: 'Listening', question: 'What did you hear?', options: ['Thank you', 'You are welcome', 'Excuse me', 'Please'], correctAnswer: 'Thank you', audioText: 'Thank you very much for your help.' },
      { id: 'q1c', type: 'Listening', question: 'What did you hear?', options: ['I am sorry', 'Excuse me', 'Pardon me', 'Bless you'], correctAnswer: 'I am sorry', audioText: 'I am sorry, I did not mean to do that.' },
      { id: 'q1d', type: 'Listening', question: 'What did you hear?', options: ['See you later', 'Have a nice day', 'Good luck', 'Take care'], correctAnswer: 'Have a nice day', audioText: 'Goodbye, and have a nice day!' },
      { id: 'q1e', type: 'Listening', question: 'What did you hear?', options: ['Welcome', 'Enter', 'Come in', 'Hello'], correctAnswer: 'Welcome', audioText: 'Welcome to our home.' },
      { id: 'q1f', type: 'Listening', question: 'What did you hear?', options: ['How old are you?', 'Where are you from?', 'What time is it?', 'How much is it?'], correctAnswer: 'Where are you from?', audioText: 'Nice to meet you, where are you from?' },
      { id: 'q1g', type: 'Listening', question: 'What did you hear?', options: ['I am fine', 'Not bad', 'Could be better', 'I am thirsty'], correctAnswer: 'I am fine', audioText: 'I am fine, thank you for asking.' },
      { id: 'q1h', type: 'Listening', question: 'What did you hear?', options: ['Wait a minute', 'Let us go', 'Hurry up', 'Stop it'], correctAnswer: 'Wait a minute', audioText: 'Please wait a minute, I am coming.' },
      { id: 'q1i', type: 'Listening', question: 'What did you hear?', options: ['Great job', 'Well done', 'Good luck', 'Happy birthday'], correctAnswer: 'Happy birthday', audioText: 'Happy birthday to you, Sarah!' },
      { id: 'q1j', type: 'Listening', question: 'What did you hear?', options: ['My name is Tom', 'I am a doctor', 'I like pizza', 'This is my cat'], correctAnswer: 'My name is Tom', audioText: 'Hello, my name is Tom and I live here.' },
    ]
  },
  {
    id: 'en-beg-speak',
    language: 'English',
    level: 'Beginner',
    type: 'Speaking',
    title: 'Introducing Yourself',
    description: 'Practice saying your name and where you are from.',
    questions: [
      { id: 'q2', type: 'Speaking', question: 'Say: "My name is John and I am from New York."', sampleAnswer: 'My name is John and I am from New York.' },
      { id: 'q2b', type: 'Speaking', question: 'Say: "Nice to meet you."', sampleAnswer: 'Nice to meet you.' },
      { id: 'q2c', type: 'Speaking', question: 'Say: "I am a student at the local university."', sampleAnswer: 'I am a student at the local university.' },
      { id: 'q2d', type: 'Speaking', question: 'Say: "I enjoy playing football on weekends."', sampleAnswer: 'I enjoy playing football on weekends.' },
      { id: 'q2e', type: 'Speaking', question: 'Say: "I have two brothers and one sister."', sampleAnswer: 'I have two brothers and one sister.' },
      { id: 'q2f', type: 'Speaking', question: 'Say: "The weather is very beautiful today."', sampleAnswer: 'The weather is very beautiful today.' },
      { id: 'q2g', type: 'Speaking', question: 'Say: "Can you help me find the library?"', sampleAnswer: 'Can you help me find the library?' },
      { id: 'q2h', type: 'Speaking', question: 'Say: "I would like to buy some fresh bread."', sampleAnswer: 'I would like to buy some fresh bread.' },
      { id: 'q2i', type: 'Speaking', question: 'Say: "Excuse me, where is the nearest bus stop?"', sampleAnswer: 'Excuse me, where is the nearest bus stop?' },
      { id: 'q2j', type: 'Speaking', question: 'Say: "Have a wonderful weekend!"', sampleAnswer: 'Have a wonderful weekend!' },
    ]
  },
  {
    id: 'en-beg-write',
    language: 'English',
    level: 'Beginner',
    type: 'Writing',
    title: 'Simple Descriptions',
    description: 'Write simple sentences about objects.',
    questions: [
      { id: 'q3', type: 'Writing', question: 'Describe your favorite fruit in two sentences.', sampleAnswer: 'My favorite fruit is an apple. It is red and sweet.' },
      { id: 'q3b', type: 'Writing', question: 'Describe your house in two sentences.', sampleAnswer: 'My house is small and white. It has a beautiful garden.' },
      { id: 'q3c', type: 'Writing', question: 'Describe your pet in two sentences.', sampleAnswer: 'I have a dog named Max. He is very friendly and brown.' },
      { id: 'q3d', type: 'Writing', question: 'Describe your favorite teacher in two sentences.', sampleAnswer: 'My favorite teacher is Mr. Smith. He is very kind and funny.' },
      { id: 'q3e', type: 'Writing', question: 'Describe your favorite color in two sentences.', sampleAnswer: 'My favorite color is blue. It reminds me of the ocean and the sky.' },
      { id: 'q3f', type: 'Writing', question: 'Describe your typical breakfast in two sentences.', sampleAnswer: 'I usually eat eggs and toast for breakfast. I also drink a glass of orange juice.' },
      { id: 'q3g', type: 'Writing', question: 'Describe your best friend in two sentences.', sampleAnswer: 'My best friend is named Sarah. We have known each other since childhood.' },
      { id: 'q3h', type: 'Writing', question: 'Describe a rainy day in two sentences.', sampleAnswer: 'A rainy day is usually grey and cool. I like to stay inside and read a book.' },
      { id: 'q3i', type: 'Writing', question: 'Describe your favorite hobby in two sentences.', sampleAnswer: 'My favorite hobby is photography. I love capturing beautiful moments with my camera.' },
      { id: 'q3j', type: 'Writing', question: 'Describe your favorite season in two sentences.', sampleAnswer: 'My favorite season is autumn. I love the colorful leaves and the crisp air.' },
    ]
  },
  {
    id: 'en-beg-comp',
    language: 'English',
    level: 'Beginner',
    type: 'Comprehension',
    title: 'Short Stories',
    description: 'Read a short paragraph and answer questions.',
    questions: [
      { id: 'q4', type: 'Comprehension', question: 'Where is the cat? "The cat is under the table."', options: ['On the table', 'Under the table', 'Beside the table', 'In the box'], correctAnswer: 'Under the table' },
      { id: 'q4b', type: 'Comprehension', question: 'What color is the car? "The blue car is fast."', options: ['Red', 'Blue', 'Green', 'Yellow'], correctAnswer: 'Blue' },
      { id: 'q4c', type: 'Comprehension', question: 'What is he eating? "He is eating a red apple."', options: ['Banana', 'Orange', 'Apple', 'Grape'], correctAnswer: 'Apple' },
      { id: 'q4d', type: 'Comprehension', question: 'Who is at the door? "A tall man is at the door."', options: ['A woman', 'A child', 'A tall man', 'A dog'], correctAnswer: 'A tall man' },
      { id: 'q4e', type: 'Comprehension', question: 'What time is it? "It is five o\'clock."', options: ['Four', 'Five', 'Six', 'Seven'], correctAnswer: 'Five' },
      { id: 'q4f', type: 'Comprehension', question: 'Where are my keys? "Your keys are inside your bag."', options: ['On the table', 'In the car', 'Inside your bag', 'At the office'], correctAnswer: 'Inside your bag' },
      { id: 'q4g', type: 'Comprehension', question: 'What is Sarah doing? "Sarah is reading a book."', options: ['Writing an email', 'Reading a book', 'Watching TV', 'Cooking dinner'], correctAnswer: 'Reading a book' },
      { id: 'q4h', type: 'Comprehension', question: 'What weather is it? "It is raining outside."', options: ['Sunny', 'Cloudy', 'Snowing', 'Raining'], correctAnswer: 'Raining' },
      { id: 'q4i', type: 'Comprehension', question: 'How is the soup? "This soup is very hot."', options: ['Cold', 'Sweet', 'Hot', 'Salty'], correctAnswer: 'Hot' },
      { id: 'q4j', type: 'Comprehension', question: 'Where do they live? "They live in a small village."', options: ['In a big city', 'In a small village', 'On an island', 'In the mountains'], correctAnswer: 'In a small village' },
    ]
  },

  // INTERMEDIATE
  {
    id: 'en-int-listen',
    language: 'English',
    level: 'Intermediate',
    type: 'Listening',
    title: 'Travel Directions',
    description: 'Listen to directions and identify the destination.',
    questions: [
      { id: 'q10', type: 'Listening', question: 'Where should you turn?', options: ['Left at the bank', 'Right at the station', 'Straight past the park', 'U-turn at the light'], correctAnswer: 'Right at the station', audioText: 'Go straight for two blocks, then turn right at the station.' },
      { id: 'q10b', type: 'Listening', question: 'What time is the train?', options: ['10:30 AM', '11:15 AM', '12:00 PM', '1:45 PM'], correctAnswer: '11:15 AM', audioText: 'The next train to London departs at eleven fifteen AM.' },
      { id: 'q10c', type: 'Listening', question: 'How much is the ticket?', options: ['Five dollars', 'Ten dollars', 'Fifteen dollars', 'Twenty dollars'], correctAnswer: 'Fifteen dollars', audioText: 'That will be fifteen dollars for a one-way ticket.' },
      { id: 'q10d', type: 'Listening', question: 'Which platform should you go to?', options: ['Platform 3', 'Platform 5', 'Platform 7', 'Platform 9'], correctAnswer: 'Platform 3', audioText: 'The train to Manchester is departing from platform three.' },
      { id: 'q10e', type: 'Listening', question: 'What is the flight number?', options: ['BA123', 'BA456', 'BA789', 'BA012'], correctAnswer: 'BA456', audioText: 'British Airways flight B-A four five six is now boarding.' },
      { id: 'q10f', type: 'Listening', question: 'Where is the baggage claim?', options: ['Next to the exit', 'Near the entrance', 'In the lower level', 'Opposite the cafe'], correctAnswer: 'In the lower level', audioText: 'You can collect your luggage from the carousel in the lower level.' },
      { id: 'q10g', type: 'Listening', question: 'How long is the delay?', options: ['Two minutes', 'Twenty minutes', 'Two hours', 'Four hours'], correctAnswer: 'Twenty minutes', audioText: 'We expect a delay of approximately twenty minutes while the plane is being refueled.' },
      { id: 'q10h', type: 'Listening', question: 'What is the seat number?', options: ['12A', '14B', '16C', '18D'], correctAnswer: '14B', audioText: 'Your seat number is fourteen-B, which is a window seat.' },
      { id: 'q10i', type: 'Listening', question: 'Where is the hotel?', options: ['By the beach', 'In the city center', 'Near the airport', 'On a mountain'], correctAnswer: 'By the beach', audioText: 'Our hotel is located right by the beach, offering stunning ocean views.' },
      { id: 'q10j', type: 'Listening', question: 'What is the wifi password?', options: ['Traveler123', 'Password456', 'Guest789', 'Welcome000'], correctAnswer: 'Traveler123', audioText: 'The wifi network name is HotelGuests and the password is Traveler one two three.' },
    ]
  },
  {
    id: 'en-int-speak',
    language: 'English',
    level: 'Intermediate',
    type: 'Speaking',
    title: 'Ordering Food',
    description: 'Practice ordering a meal at a restaurant.',
    questions: [
      { id: 'q11', type: 'Speaking', question: 'Say: "I would like to order a cheeseburger with fries, please."', sampleAnswer: 'I would like to order a cheeseburger with fries, please.' },
      { id: 'q11b', type: 'Speaking', question: 'Say: "Could I have the bill, please?"', sampleAnswer: 'Could I have the bill, please?' },
      { id: 'q11c', type: 'Speaking', question: 'Say: "Is there a vegetarian option available?"', sampleAnswer: 'Is there a vegetarian option available?' },
      { id: 'q11d', type: 'Speaking', question: 'Say: "Does this dish contain any nuts?"', sampleAnswer: 'Does this dish contain any nuts?' },
      { id: 'q11e', type: 'Speaking', question: 'Say: "I have a reservation for two people at seven o\'clock."', sampleAnswer: 'I have a reservation for two people at seven o\'clock.' },
      { id: 'q11f', type: 'Speaking', question: 'Say: "Could we have a table by the window, please?"', sampleAnswer: 'Could we have a table by the window, please?' },
      { id: 'q11g', type: 'Speaking', question: 'Say: "I am allergic to gluten, can you recommend something?"', sampleAnswer: 'I am allergic to gluten, can you recommend something?' },
      { id: 'q11h', type: 'Speaking', question: 'Say: "What are the specials for today?"', sampleAnswer: 'What are the specials for today?' },
      { id: 'q11i', type: 'Speaking', question: 'Say: "Everything was delicious, thank you!"', sampleAnswer: 'Everything was delicious, thank you!' },
      { id: 'q11j', type: 'Speaking', question: 'Say: "Could I have a glass of tap water, please?"', sampleAnswer: 'Could I have a glass of tap water, please?' },
    ]
  },
  {
    id: 'en-int-write',
    language: 'English',
    level: 'Intermediate',
    type: 'Writing',
    title: 'Email Writing',
    description: 'Write a short formal email.',
    questions: [
      { id: 'q12', type: 'Writing', question: 'Write a short email to your boss asking for a day off.', sampleAnswer: 'Dear Boss, I would like to request a day off next Friday. Thank you.' },
      { id: 'q12b', type: 'Writing', question: 'Write a short email to a friend inviting them to a party.', sampleAnswer: 'Hey! I am having a party this Saturday. Hope you can come!' },
      { id: 'q12c', type: 'Writing', question: 'Write a short complaint email to a customer service department.', sampleAnswer: 'Dear Customer Service, I am writing to complain about a faulty product I recently purchased.' },
      { id: 'q12d', type: 'Writing', question: 'Write a short thank you note to a colleague for their help.', sampleAnswer: 'Dear Mark, thank you so much for your assistance with the project yesterday.' },
      { id: 'q12e', type: 'Writing', question: 'Write a short RSVP to a wedding invitation.', sampleAnswer: 'Dear Jane and John, thank you for the invitation. I would be delighted to attend.' },
      { id: 'q12f', type: 'Writing', question: 'Write a short reminder to a teammate about a meeting.', sampleAnswer: 'Hi everyone, just a quick reminder about our team meeting at 2 PM today.' },
      { id: 'q12g', type: 'Writing', question: 'Write a short inquiry to a hotel about room availability.', sampleAnswer: 'Hello, I would like to inquire about room availability for the first week of June.' },
      { id: 'q12h', type: 'Writing', question: 'Write a short feedback email about a recent seminar.', sampleAnswer: 'Dear organizers, the seminar was very informative. I especially liked the case studies.' },
      { id: 'q12i', type: 'Writing', question: 'Write a short introductory email to a new client.', sampleAnswer: 'Dear Mr. Lee, it is a pleasure to connect with you. I am the account manager for your region.' },
      { id: 'q12j', type: 'Writing', question: 'Write a short out-of-office response.', sampleAnswer: 'Thank you for your email. I am currently out of the office and will return on Monday.' },
    ]
  },
  {
    id: 'en-int-comp',
    language: 'English',
    level: 'Intermediate',
    type: 'Comprehension',
    title: 'News Articles',
    description: 'Read a news snippet and answer questions.',
    questions: [
      { id: 'q13', type: 'Comprehension', question: 'What happened in the city? "A new park opened in the city center today."', options: ['A park closed', 'A park opened', 'A building fell', 'A road was built'], correctAnswer: 'A park opened' },
      { id: 'q13b', type: 'Comprehension', question: 'Why was the flight delayed? "The flight was delayed due to heavy fog."', options: ['Engine trouble', 'Heavy fog', 'Late passengers', 'Security check'], correctAnswer: 'Heavy fog' },
      { id: 'q13c', type: 'Comprehension', question: 'Who won the game? "The home team won the championship after a thrilling final."', options: ['The away team', 'The home team', 'It was a draw', 'The game was cancelled'], correctAnswer: 'The home team' },
      { id: 'q13d', type: 'Comprehension', question: 'What is the report about? "The economic report indicates a steady rise in inflation levels."', options: ['Falling prices', 'Rising inflation', 'Stock market crash', 'Agricultural trade'], correctAnswer: 'Rising inflation' },
      { id: 'q13e', type: 'Comprehension', question: 'Where did the accident occur? "The minor accident occurred at the intersection of Main and Oak Streets."', options: ['In a parking lot', 'At the airport', 'At the intersection', 'On a highway'], correctAnswer: 'At the intersection' },
      { id: 'q13f', type: 'Comprehension', question: 'What is the main topic of the article? "Researchers have discovered a new species of deep-sea jellyfish."', options: ['Space exploration', 'Deep-sea jellyfish', 'Desert animals', 'Mountain hiking'], correctAnswer: 'Deep-sea jellyfish' },
      { id: 'q13g', type: 'Comprehension', question: 'Who is the notice for? "This notice is for all residents of the Northwood apartment complex."', options: ['Office workers', 'Apartment residents', 'Factory employees', 'Hospital staff'], correctAnswer: 'Apartment residents' },
      { id: 'q13h', type: 'Comprehension', question: 'What is the purpose of the event? "The charity event aims to raise funds for the local children\'s hospital."', options: ['To sell cars', 'To raise funds', 'To celebrate a holiday', 'To build a new park'], correctAnswer: 'To raise funds' },
      { id: 'q13i', type: 'Comprehension', question: 'Which department is hiring? "The sales department is currently seeking experienced representatives."', options: ['IT department', 'HR department', 'Sales department', 'Legal department'], correctAnswer: 'Sales department' },
      { id: 'q13j', type: 'Comprehension', question: 'What time does the store close? "Our store hours have changed; we now close at 9:00 PM on weekdays."', options: ['6:00 PM', '8:00 PM', '9:00 PM', '10:00 PM'], correctAnswer: '9:00 PM' },
    ]
  },

  // ADVANCED
  {
    id: 'en-adv-listen',
    language: 'English',
    level: 'Advanced',
    type: 'Listening',
    title: 'Academic Lectures',
    description: 'Listen to a short lecture and identify the main theme.',
    questions: [
      { id: 'q20', type: 'Listening', question: 'What is the lecture about?', options: ['Climate change', 'Ancient history', 'Quantum physics', 'Modern art'], correctAnswer: 'Climate change', audioText: 'Today we will discuss the impact of rising sea levels on coastal cities due to global warming.' },
      { id: 'q20b', type: 'Listening', question: 'What is the speaker\'s main concern?', options: ['Economic growth', 'Public health', 'Environmental stability', 'Technological advancement'], correctAnswer: 'Environmental stability', audioText: 'The primary concern of our research is the long-term stability of the ecosystem.' },
      { id: 'q20c', type: 'Listening', question: 'What industry is being discussed?', options: ['Agriculture', 'Manufacturing', 'Technology', 'Tourism'], correctAnswer: 'Technology', audioText: 'The rapid advancement of artificial intelligence is reshaping the global technology landscape.' },
      { id: 'q20d', type: 'Listening', question: 'What is the main topic of the presentation?', options: ['Dietary habits', 'Exercise routines', 'Mental health', 'Sleep patterns'], correctAnswer: 'Mental health', audioText: 'Maintaining a healthy work-life balance is crucial for long-term mental well-being and productivity.' },
      { id: 'q20e', type: 'Listening', question: 'What historical period is mentioned?', options: ['Renaissance', 'Industrial Revolution', 'Middle Ages', 'Digital Age'], correctAnswer: 'Renaissance', audioText: 'The Renaissance marked a significant shift in European art, science, and philosophy.' },
      { id: 'q20f', type: 'Listening', question: 'What is the speaker recommending?', options: ['Higher taxes', 'Lower interest rates', 'Increased regulation', 'Market liberalization'], correctAnswer: 'Lower interest rates', audioText: 'To stimulate economic growth, the central bank is considering a reduction in interest rates.' },
      { id: 'q20g', type: 'Listening', question: 'What is the focus of the study?', options: ['Urban planning', 'Marine biology', 'Space exploration', 'Renewable energy'], correctAnswer: 'Renewable energy', audioText: 'This study evaluates the efficiency of various renewable energy sources in reducing carbon emissions.' },
      { id: 'q20h', type: 'Listening', question: 'What is the speaker describing?', options: ['A new product', 'A historical event', 'A scientific theory', 'A cultural tradition'], correctAnswer: 'A scientific theory', audioText: 'The theory of relativity has fundamentally changed our understanding of time and space.' },
      { id: 'q20i', type: 'Listening', question: 'What is the primary challenge mentioned?', options: ['Funding', 'Resource scarcity', 'Logistics', 'Communication'], correctAnswer: 'Resource scarcity', audioText: 'One of the greatest challenges facing the projects is the scarcity of essential resources.' },
      { id: 'q20j', type: 'Listening', question: 'What is the tone of the speaker?', options: ['Optimistic', 'Cautious', 'Indifferent', 'Aggressive'], correctAnswer: 'Cautious', audioText: 'While the initial results are promising, we must remain cautious about the long-term implications.' },
    ]
  },
  {
    id: 'en-adv-speak',
    language: 'English',
    level: 'Advanced',
    type: 'Speaking',
    title: 'Debating Topics',
    description: 'Express your opinion on a complex topic.',
    questions: [
      { id: 'q21', type: 'Speaking', question: 'Argue for or against the use of AI in education.', sampleAnswer: 'I believe AI in education can personalize learning, but it must be used ethically to avoid bias.' },
      { id: 'q21b', type: 'Speaking', question: 'Discuss the impact of social media on modern democracy.', sampleAnswer: 'Social media has revolutionized communication but also facilitated the spread of misinformation.' },
      { id: 'q21c', type: 'Speaking', question: 'Explain the importance of universal basic income.', sampleAnswer: 'Universal basic income could provide a safety net for workers displaced by automation.' },
      { id: 'q21d', type: 'Speaking', question: 'Describe the benefits of space exploration for humanity.', sampleAnswer: 'Space exploration drives technological innovation and inspires future generations of scientists.' },
      { id: 'q21e', type: 'Speaking', question: 'Discuss the ethical implications of genetic engineering.', sampleAnswer: 'Genetic engineering offers potential cures for diseases but raises significant ethical concerns about human enhancement.' },
      { id: 'q21f', type: 'Speaking', question: 'Argue the case for or against nuclear energy.', sampleAnswer: 'Nuclear energy provides a low-carbon source of power but presents challenges regarding waste disposal and safety.' },
      { id: 'q21g', type: 'Speaking', question: 'Explain how globalization has affected local cultures.', sampleAnswer: 'Globalization has led to cultural exchange but also threatens the preservation of unique local traditions.' },
      { id: 'q21h', type: 'Speaking', question: 'Discuss the role of art in social change.', sampleAnswer: 'Art serves as a powerful medium for challenging societal norms and advocating for political reform.' },
      { id: 'q21i', type: 'Speaking', question: 'Argue for the implementation of shorter work weeks.', sampleAnswer: 'A four-day work week could improve employee well-being and productivity while reducing burnout.' },
      { id: 'q21j', type: 'Speaking', question: 'Discuss the impact of remote work on urban planning.', sampleAnswer: 'The shift to remote work is forcing cities to rethink their reliance on commercial office space.' },
    ]
  },
  {
    id: 'en-adv-write',
    language: 'English',
    level: 'Advanced',
    type: 'Writing',
    title: 'Essay Writing',
    description: 'Write a persuasive essay.',
    questions: [
      { id: 'q22', type: 'Writing', question: 'Write a paragraph about the importance of space exploration.', sampleAnswer: 'Space exploration is vital for the survival of humanity as it drives innovation and helps us understand our place in the universe.' },
      { id: 'q22b', type: 'Writing', question: 'Write a paragraph about the benefits of a plant-based diet.', sampleAnswer: 'A plant-based diet can significantly reduce one\'s carbon footprint and improve overall health.' },
      { id: 'q22c', type: 'Writing', question: 'Write a paragraph discussing the pros and cons of electric vehicles.', sampleAnswer: 'Electric vehicles reduce tailpipe emissions but require significant improvements in charging infrastructure and battery technology.' },
      { id: 'q22d', type: 'Writing', question: 'Write a paragraph on the role of education in reducing inequality.', sampleAnswer: 'Quality education provides individuals with the skills needed to escape poverty and promotes social mobility.' },
      { id: 'q22e', type: 'Writing', question: 'Write a paragraph about the impact of artificial intelligence on the job market.', sampleAnswer: 'AI will likely automate many routine tasks but also create new opportunities in technology and data analysis.' },
      { id: 'q22f', type: 'Writing', question: 'Write a paragraph about the importance of preserving biodiversity.', sampleAnswer: 'Biodiversity is essential for maintaining ecosystem services that support life on Earth, such as pollination and water purification.' },
      { id: 'q22g', type: 'Writing', question: 'Write a paragraph on the challenges of urban overpopulation.', sampleAnswer: 'Urban overpopulation leads to housing shortages, increased pollution, and strain on public infrastructure.' },
      { id: 'q22h', type: 'Writing', question: 'Write a paragraph about the cultural significance of traditional festivals.', sampleAnswer: 'Traditional festivals strengthen community bonds and preserve cultural heritage for future generations.' },
      { id: 'q22i', type: 'Writing', question: 'Write a paragraph discussing the ethics of animal testing in medicine.', sampleAnswer: 'Animal testing has led to medical breakthroughs but raises concerns about the suffering inflicted on sentient beings.' },
      { id: 'q22j', type: 'Writing', question: 'Write a paragraph on the impact of climate change on migration patterns.', sampleAnswer: 'Rising temperatures and extreme weather events are forcing millions of people to leave their homes in search of safer environments.' },
    ]
  },
  {
    id: 'en-adv-comp',
    language: 'English',
    level: 'Advanced',
    type: 'Comprehension',
    title: 'Literary Analysis',
    description: 'Read a poem or prose and analyze its meaning.',
    questions: [
      { id: 'q23', type: 'Comprehension', question: 'What is the tone of the passage? "The dark clouds loomed over the silent, empty streets."', options: ['Joyful', 'Ominous', 'Exciting', 'Humorous'], correctAnswer: 'Ominous' },
      { id: 'q23b', type: 'Comprehension', question: 'What does the "river" symbolize in this context? "The river flowed endlessly, carrying the memories of the past."', options: ['Time', 'Death', 'Life', 'Sorrow'], correctAnswer: 'Time' },
      { id: 'q23c', type: 'Comprehension', question: 'What does the phrase "silver lining" mean in a sentence like "Every cloud has a silver lining"?', options: ['A storm is coming', 'A bright spot in a bad situation', 'Actual silver in the sky', 'Rain is ending'], correctAnswer: 'A bright spot in a bad situation' },
      { id: 'q23d', type: 'Comprehension', question: 'Describe the mood: "Laughter echoed through the sun-drenched meadow as children played."', options: ['Melancholy', 'Cheerful', 'Tense', 'Frightening'], correctAnswer: 'Cheerful' },
      { id: 'q23e', type: 'Comprehension', question: 'Identify the metaphor: "His words were a warm blanket on a cold winter night."', options: ['Warm blanket', 'Cold winter night', 'His words', 'A blanket'], correctAnswer: 'Warm blanket' },
      { id: 'q23f', type: 'Comprehension', question: 'What does the color "green" often suggest in literature besides nature?', options: ['Envy', 'Anger', 'Cowardice', 'Melancholy'], correctAnswer: 'Envy' },
      { id: 'q23g', type: 'Comprehension', question: 'What literary device is used here: "The wind whispered through the trees"?', options: ['Personification', 'Simile', 'Hyperbole', 'Alliteration'], correctAnswer: 'Personification' },
      { id: 'q23h', type: 'Comprehension', question: 'What does a "phoenix" typically represent?', options: ['Endings', 'Rebirth', 'War', 'Evil'], correctAnswer: 'Rebirth' },
      { id: 'q23i', type: 'Comprehension', question: 'In the sentence "She was as brave as a lion", which device is used?', options: ['Simile', 'Metaphor', 'Onomatopoeia', 'Oxymoron'], correctAnswer: 'Simile' },
      { id: 'q23j', type: 'Comprehension', question: 'What is the theme of a story where a character learns to appreciate their family after losing everything?', options: ['Revenge', 'Redemption', 'Gratitude', 'Betrayal'], correctAnswer: 'Gratitude' },
    ]
  },

  // ==========================================
  // MALAY
  // ==========================================
  
  // BEGINNER
  {
    id: 'ms-beg-listen',
    language: 'Malay',
    level: 'Beginner',
    type: 'Listening',
    title: 'Ucapan Asas',
    description: 'Dengar ucapan biasa dan kenal pasti.',
    questions: [
      { id: 'q5', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Selamat pagi', 'Selamat malam', 'Terima kasih', 'Sama-sama'], correctAnswer: 'Selamat pagi', audioText: 'Selamat pagi, apa khabar?' },
      { id: 'q5b', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Sila duduk', 'Jemput makan', 'Apa khabar', 'Selamat jalan'], correctAnswer: 'Apa khabar', audioText: 'Apa khabar semua?' },
      { id: 'q5c', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Maafkan saya', 'Tolong saya', 'Sama-sama', 'Terima kasih'], correctAnswer: 'Maafkan saya', audioText: 'Maafkan saya, saya lambat.' },
      { id: 'q5d', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Selamat datang', 'Selamat tinggal', 'Selamat petang', 'Selamat siang'], correctAnswer: 'Selamat datang', audioText: 'Selamat datang ke Malaysia!' },
      { id: 'q5e', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Berapa harga ini?', 'Di mana tandas?', 'Siapa nama anda?', 'Apa khabar?'], correctAnswer: 'Siapa nama anda?', audioText: 'Siapa nama anda? Nama saya Ali.' },
      { id: 'q5f', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Saya lapar', 'Saya dahaga', 'Saya penat', 'Saya mengantuk'], correctAnswer: 'Saya lapar', audioText: 'Saya berasa lapar sekarang.' },
      { id: 'q5g', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Hari ini cerah', 'Hari ini hujan', 'Hari ini mendung', 'Hari ini berangin'], correctAnswer: 'Hari ini hujan', audioText: 'Nampaknya hari ini akan hujan lebat.' },
      { id: 'q5h', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Satu', 'Dua', 'Tiga', 'Empat'], correctAnswer: 'Tiga', audioText: 'Sila ambil tiga biji epal itu.' },
      { id: 'q5i', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Besar', 'Kecil', 'Tinggi', 'Rendah'], correctAnswer: 'Besar', audioText: 'Rumah itu sangat besar.' },
      { id: 'q5j', type: 'Listening', question: 'Apa yang anda dengar?', options: ['Laju', 'Perlahan', 'Cantik', 'Buruk'], correctAnswer: 'Cantik', audioText: 'Bunga itu sungguh cantik.' },
    ]
  },
  {
    id: 'ms-beg-speak',
    language: 'Malay',
    level: 'Beginner',
    type: 'Speaking',
    title: 'Kenalkan Diri',
    description: 'Berlatih menyebut nama dan asal anda.',
    questions: [
      { id: 'q30', type: 'Speaking', question: 'Sebut: "Nama saya Ali dan saya dari Kuala Lumpur."', sampleAnswer: 'Nama saya Ali dan saya dari Kuala Lumpur.' },
      { id: 'q30b', type: 'Speaking', question: 'Sebut: "Saya suka makan nasi lemak."', sampleAnswer: 'Saya suka makan nasi lemak.' },
      { id: 'q30c', type: 'Speaking', question: 'Sebut: "Umur saya dua puluh tahun."', sampleAnswer: 'Umur saya dua puluh tahun.' },
      { id: 'q30d', type: 'Speaking', question: 'Sebut: "Saya bekerja sebagai seorang guru."', sampleAnswer: 'Saya bekerja sebagai seorang guru.' },
      { id: 'q30e', type: 'Speaking', question: 'Sebut: "Hobi saya ialah bermain badminton."', sampleAnswer: 'Hobi saya ialah bermain badminton.' },
      { id: 'q30f', type: 'Speaking', question: 'Sebut: "Saya mempunyai dua orang abang."', sampleAnswer: 'Saya mempunyai dua orang abang.' },
      { id: 'q30g', type: 'Speaking', question: 'Sebut: "Warna kegemaran saya ialah biru."', sampleAnswer: 'Warna kegemaran saya ialah biru.' },
      { id: 'q30h', type: 'Speaking', question: 'Sebut: "Saya tinggal di sebuah rumah flat."', sampleAnswer: 'Saya tinggal di sebuah rumah flat.' },
      { id: 'q30i', type: 'Speaking', question: 'Sebut: "Selamat berkenalan dengan anda."', sampleAnswer: 'Selamat berkenalan dengan anda.' },
      { id: 'q30j', type: 'Speaking', question: 'Sebut: "Saya gembira dapat berjumpa dengan kamu."', sampleAnswer: 'Saya gembira dapat berjumpa dengan kamu.' },
    ]
  },
  {
    id: 'ms-beg-write',
    language: 'Malay',
    level: 'Beginner',
    type: 'Writing',
    title: 'Ayat Mudah',
    description: 'Tulis ayat mudah tentang diri anda.',
    questions: [
      { id: 'q31', type: 'Writing', question: 'Tulis satu ayat tentang hobi anda.', sampleAnswer: 'Hobi saya ialah membaca buku.' },
      { id: 'q31b', type: 'Writing', question: 'Tulis satu ayat tentang keluarga anda.', sampleAnswer: 'Saya ada tiga orang adik-beradik.' },
      { id: 'q31c', type: 'Writing', question: 'Tulis satu ayat tentang makanan kegemaran anda.', sampleAnswer: 'Makanan kegemaran saya ialah sate ayam.' },
      { id: 'q31d', type: 'Writing', question: 'Tulis satu ayat tentang tempat tinggal anda.', sampleAnswer: 'Saya tinggal di bandar Melaka.' },
      { id: 'q31e', type: 'Writing', question: 'Tulis satu ayat tentang cuaca hari ini.', sampleAnswer: 'Cuaca hari ini sangat panas dan terik.' },
      { id: 'q31f', type: 'Writing', question: 'Tulis satu ayat tentang kawan baik anda.', sampleAnswer: 'Kawan baik saya bernama Ahmad, dia sangat baik hati.' },
      { id: 'q31g', type: 'Writing', question: 'Tulis satu ayat tentang cita-cita anda.', sampleAnswer: 'Cita-cita saya adalah untuk menjadi seorang doktor.' },
      { id: 'q31h', type: 'Writing', question: 'Tulis satu ayat tentang sekolah anda.', sampleAnswer: 'Sekolah saya terletak berhampiran dengan taman perumahan.' },
      { id: 'q31i', type: 'Writing', question: 'Tulis satu ayat tentang binatang peliharaan anda.', sampleAnswer: 'Saya membela seekor kucing yang comel bernama Meow.' },
      { id: 'q31j', type: 'Writing', question: 'Tulis satu ayat tentang rancangan hujung minggu anda.', sampleAnswer: 'Hujung minggu ini saya bercadang untuk pergi ke pantai.' },
    ]
  },
  {
    id: 'ms-beg-comp',
    language: 'Malay',
    level: 'Beginner',
    type: 'Comprehension',
    title: 'Cerita Pendek',
    description: 'Baca perenggan pendek dan jawab soalan.',
    questions: [
      { id: 'q32', type: 'Comprehension', question: 'Di mana kucing itu? "Kucing itu ada di atas kerusi."', options: ['Di bawah meja', 'Di atas kerusi', 'Di dalam raga', 'Di luar rumah'], correctAnswer: 'Di atas kerusi' },
      { id: 'q32b', type: 'Comprehension', question: 'Warna apa kereta itu? "Kereta merah itu laju."', options: ['Biru', 'Merah', 'Kuning', 'Hijau'], correctAnswer: 'Merah' },
      { id: 'q32c', type: 'Comprehension', question: 'Siapa yang datang? "Seorang lelaki tinggi datang ke rumah."', options: ['Budak kecil', 'Lelaki tinggi', 'Wanita tua', 'Kucing'], correctAnswer: 'Lelaki tinggi' },
      { id: 'q32d', type: 'Comprehension', question: 'Berapa biji epal yang ada? "Ada lima biji epal di dalam bakul."', options: ['Tiga', 'Empat', 'Lima', 'Enam'], correctAnswer: 'Lima' },
      { id: 'q32e', type: 'Comprehension', question: 'Pukul berapa sekarang? "Sekarang pukul lapan malam."', options: ['Pagi', 'Tengah hari', 'Petang', 'Malam'], correctAnswer: 'Malam' },
      { id: 'q32f', type: 'Comprehension', question: 'Di mana Ahmad bekerja? "Ahmad bekerja di sebuah bank di bandar."', options: ['Hospital', 'Sekolah', 'Bank', 'Kilang'], correctAnswer: 'Bank' },
      { id: 'q32g', type: 'Comprehension', question: 'Apa yang emak masak? "Emak sedang masak nasi goreng untuk sarapan."', options: ['Nasi lemak', 'Mee goreng', 'Nasi goreng', 'Roti canai'], correctAnswer: 'Nasi goreng' },
      { id: 'q32h', type: 'Comprehension', question: 'Kenapa Siti menangis? "Siti menangis kerana kakinya luka terjatuh."', options: ['Lapar', 'Sakit', 'Sedih', 'Haus'], correctAnswer: 'Sakit' },
      { id: 'q32i', type: 'Comprehension', question: 'Di mana budak-budak itu bermain? "Budak-budak itu sedang bermain bola di padang."', options: ['Rumah', 'Padang', 'Sekolah', 'Taman'], correctAnswer: 'Padang' },
      { id: 'q32j', type: 'Comprehension', question: 'Apa yang dibeli oleh ayah? "Ayah beli sebuah buku cerita baru untuk saya."', options: ['Mainan', 'Baju', 'Buku cerita', 'Kasut'], correctAnswer: 'Buku cerita' },
    ]
  },

  // INTERMEDIATE
  {
    id: 'ms-int-listen',
    language: 'Malay',
    level: 'Intermediate',
    type: 'Listening',
    title: 'Pesanan Makanan',
    description: 'Dengar pesanan di restoran.',
    questions: [
      { id: 'q33', type: 'Listening', question: 'Apa yang dipesan?', options: ['Nasi lemak', 'Mee goreng', 'Satay ayam', 'Roti canai'], correctAnswer: 'Nasi lemak', audioText: 'Saya mahu satu pinggan nasi lemak dan teh tarik.' },
      { id: 'q33b', type: 'Listening', question: 'Berapa harga makanan itu?', options: ['Lima ringgit', 'Sepuluh ringgit', 'Lapan ringgit', 'Dua belas ringgit'], correctAnswer: 'Lapan ringgit', audioText: 'Semuanya lapan ringgit sahaja.' },
      { id: 'q33c', type: 'Listening', question: 'Ke mana mereka mahu pergi?', options: ['Pantai', 'Taman', 'Pasar raya', 'Wayang'], correctAnswer: 'Pasar raya', audioText: 'Jom kita pergi ke pasar raya untuk beli barang dapur.' },
      { id: 'q33d', type: 'Listening', question: 'Bila bas akan sampai?', options: ['5 minit lagi', '10 minit lagi', '15 minit lagi', '20 minit lagi'], correctAnswer: '15 minit lagi', audioText: 'Bas itu dijangka sampai dalam masa lima belas minit lagi.' },
      { id: 'q33e', type: 'Listening', question: 'Apa yang sedang ditonton?', options: ['Berita', 'Kartun', 'Drama', 'Sukan'], correctAnswer: 'Sukan', audioText: 'Ayah sedang menonton perlawanan bola sepak di televisyen.' },
      { id: 'q33f', type: 'Listening', question: 'Siapakah yang menelefon?', options: ['Ali', 'Abu', 'Siti', 'Aminah'], correctAnswer: 'Abu', audioText: 'Hello, ini Abu. Adakah Ali ada di rumah?' },
      { id: 'q33g', type: 'Listening', question: 'Di mana kunci kereta?', options: ['Atas meja', 'Dalam poket', 'Bawah kerusi', 'Dalam laci'], correctAnswer: 'Atas meja', audioText: 'Kunci kereta ada di atas meja makan, tolong ambilkan.' },
      { id: 'q33h', type: 'Listening', question: 'Mengapa dia tidak datang?', options: ['Demam', 'Bukan harinya', 'Lupa', 'Sibuk'], correctAnswer: 'Demam', audioText: 'Saya minta maaf, saya tidak dapat datang kerana saya sedang demam.' },
      { id: 'q33i', type: 'Listening', question: 'Berapa orang yang hadir?', options: ['10 orang', '20 orang', '5 orang', '15 orang'], correctAnswer: '20 orang', audioText: 'Seramai dua puluh orang telah hadir ke mesyuarat pagi tadi.' },
      { id: 'q33j', type: 'Listening', question: 'Apa warna baju barunya?', options: ['Hijau', 'Biru', 'Kuning', 'Putih'], correctAnswer: 'Biru', audioText: 'Wah, cantiknya baju baru kamu yang berwarna biru itu!' },
    ]
  },
  {
    id: 'ms-int-speak',
    language: 'Malay',
    level: 'Intermediate',
    type: 'Speaking',
    title: 'Bercerita',
    description: 'Ceritakan tentang percutian anda.',
    questions: [
      { id: 'q34', type: 'Speaking', question: 'Sebut: "Minggu lepas saya pergi ke Pulau Langkawi bersama keluarga."', sampleAnswer: 'Minggu lepas saya pergi ke Pulau Langkawi bersama keluarga.' },
      { id: 'q34b', type: 'Speaking', question: 'Sebut: "Makanan di sana sangat sedap dan murah."', sampleAnswer: 'Makanan di sana sangat sedap dan murah.' },
      { id: 'q34c', type: 'Speaking', question: 'Sebut: "Kami melawat Makam Mahsuri dan menaiki kereta kabel."', sampleAnswer: 'Kami melawat Makam Mahsuri dan menaiki kereta kabel.' },
      { id: 'q34d', type: 'Speaking', question: 'Sebut: "Pemandangan dari puncak gunung sangat menakjubkan."', sampleAnswer: 'Pemandangan dari puncak gunung sangat menakjubkan.' },
      { id: 'q34e', type: 'Speaking', question: 'Sebut: "Saya berharap dapat kembali lagi ke sana pada masa depan."', sampleAnswer: 'Saya berharap dapat kembali lagi ke sana pada masa depan.' },
      { id: 'q34f', type: 'Speaking', question: 'Sebut: "Ibu bapa saya sangat gembira dapat berehat di tepi pantai."', sampleAnswer: 'Ibu bapa saya sangat gembira dapat berehat di tepi pantai.' },
      { id: 'q34g', type: 'Speaking', question: 'Sebut: "Adik saya asyik bermain pasir dan membina istana pasir."', sampleAnswer: 'Adik saya asyik bermain pasir dan membina istana pasir.' },
      { id: 'q34h', type: 'Speaking', question: 'Sebut: "Kami juga sempat membeli-belah di kedai bebas cukai."', sampleAnswer: 'Kami juga sempat membeli-belah di kedai bebas cukai.' },
      { id: 'q34i', type: 'Speaking', question: 'Sebut: "Secara keseluruhannya, percutian itu sangat bermakna bagi kami."', sampleAnswer: 'Secara keseluruhannya, percutian itu sangat bermakna bagi kami.' },
      { id: 'q34j', type: 'Speaking', question: 'Sebut: "Terima kasih kerana mendengar cerita percutian saya."', sampleAnswer: 'Terima kasih kerana mendengar cerita percutian saya.' },
    ]
  },
  {
    id: 'ms-int-write',
    language: 'Malay',
    level: 'Intermediate',
    type: 'Writing',
    title: 'Surat Tidak Rasmi',
    description: 'Tulis surat ringkas kepada kawan.',
    questions: [
      { id: 'q35', type: 'Writing', question: 'Tulis pesanan ringkas kepada kawan untuk berjumpa.', sampleAnswer: 'Hai Ali, jom kita jumpa di kedai kopi petang ini.' },
      { id: 'q35b', type: 'Writing', question: 'Tulis ucapan hari jadi kepada kawan anda.', sampleAnswer: 'Selamat hari jadi! Semoga panjang umur dan murah rezeki.' },
      { id: 'q35c', type: 'Writing', question: 'Tulis nota ringkas untuk memberitahu ibu anda akan pulang lewat.', sampleAnswer: 'Mak, saya akan pulang lewat hari ini kerana ada kelas tambahan.' },
      { id: 'q35d', type: 'Writing', question: 'Tulis senarai barang dapur yang perlu dibeli.', sampleAnswer: 'Sila beli telur, susu, roti, dan minyak masak di pasar raya.' },
      { id: 'q35e', type: 'Writing', question: 'Tulis pesanan ringkas untuk membatalkan temu janji.', sampleAnswer: 'Saya minta maaf, saya tidak dapat hadir ke perjumpaan kita hari ini.' },
      { id: 'q35f', type: 'Writing', question: 'Tulis ucapan terima kasih atas hadiah yang diberikan.', sampleAnswer: 'Terima kasih banyak atas hadiah hari jadi yang sangat cantik itu!' },
      { id: 'q35g', type: 'Writing', question: 'Tulis nota ringkas kepada jiran untuk menjaga rumah.', sampleAnswer: 'Encik Ahmad, tolong perhatikan rumah saya semasa saya bercuti.' },
      { id: 'q35h', type: 'Writing', question: 'Tulis pesanan untuk mengajak kawan pergi bersenam.', sampleAnswer: 'Jom kita pergi berjoging di taman petang esok.' },
      { id: 'q35i', type: 'Writing', question: 'Tulis ucapan tahniah atas kejayaan kawan dalam peperiksaan.', sampleAnswer: 'Tahniah! Saya tumpang gembira atas kejayaan cemerlang kamu.' },
      { id: 'q35j', type: 'Writing', question: 'Tulis nota untuk memesan makanan melalui aplikasi.', sampleAnswer: 'Tolong hantarkan satu set nasi lemak ke alamat rumah saya.' },
    ]
  },
  {
    id: 'ms-int-comp',
    language: 'Malay',
    level: 'Intermediate',
    type: 'Comprehension',
    title: 'Berita Tempatan',
    description: 'Baca berita ringkas dan jawab soalan.',
    questions: [
      { id: 'q36', type: 'Comprehension', question: 'Apa yang berlaku? "Hujan lebat menyebabkan banjir di beberapa kawasan."', options: ['Kemarau', 'Banjir', 'Ribut', 'Gempa bumi'], correctAnswer: 'Banjir' },
      { id: 'q36b', type: 'Comprehension', question: 'Mengapa jalan ditutup? "Jalan ditutup kerana ada kerja pembaikan."', options: ['Kemalangan', 'Kerja pembaikan', 'Banjir', 'Perarakan'], correctAnswer: 'Kerja pembaikan' },
      { id: 'q36c', type: 'Comprehension', question: 'Siapakah yang memenangi perlawanan itu? "Pasukan sekolah kita berjaya merangkul pingat emas."', options: ['Pasukan lawan', 'Pasukan sekolah kita', 'Tiada pemenang', 'Perlawanan dibatalkan'], correctAnswer: 'Pasukan sekolah kita' },
      { id: 'q36d', type: 'Comprehension', question: 'Di manakah pameran itu diadakan? "Pameran buku itu akan berlangsung di Pusat Konvensyen esok."', options: ['Perpustakaan', 'Sekolah', 'Pusat Konvensyen', 'Dewan bandaraya'], correctAnswer: 'Pusat Konvensyen' },
      { id: 'q36e', type: 'Comprehension', question: 'Apakah punca kemalangan tersebut? "Kemalangan itu berpunca daripada kerosakan brek bas."', options: ['Pemandu mengantuk', 'Kerosakan brek', 'Jalan licin', 'Lampu isyarat rosak'], correctAnswer: 'Kerosakan brek' },
      { id: 'q36f', type: 'Comprehension', question: 'Bila kedai ini akan dibuka semula? "Kedai kami akan mula beroperasi semula pada hari Isnin depan."', options: ['Hari ini', 'Esok', 'Hari Sabtu', 'Hari Isnin depan'], correctAnswer: 'Hari Isnin depan' },
      { id: 'q36g', type: 'Comprehension', question: 'Apa yang perlu dibawa oleh peserta? "Peserta diminta membawa botol air dan kasut sukan sendiri."', options: ['Buku dan pen', 'Botol air dan kasut sukan', 'Makanan tengah hari', 'Baju hujan'], correctAnswer: 'Botol air dan kasut sukan' },
      { id: 'q36h', type: 'Comprehension', question: 'Siapa yang memberikan ucapan? "Guru Besar menyampaikan ucapan perasmian pada pagi tadi."', options: ['Ketua kelas', 'Guru kelas', 'Guru Besar', 'Menteri'], correctAnswer: 'Guru Besar' },
      { id: 'q36i', type: 'Comprehension', question: 'Berapakah jumlah kehadiran? "Seramai seratus orang penduduk telah hadir ke gotong-royong itu."', options: ['Lima puluh orang', 'Lapan puluh orang', 'Seratus orang', 'Dua ratus orang'], correctAnswer: 'Seratus orang' },
      { id: 'q36j', type: 'Comprehension', question: 'Mengapa pesakit itu dibawa ke hospital? "Pesakit itu dikejarkan ke hospital kerana mengalami sesak nafas."', options: ['Sakit perut', 'Patah kaki', 'Sesak nafas', 'Demam panas'], correctAnswer: 'Sesak nafas' },
    ]
  },

  // ADVANCED
  {
    id: 'ms-adv-listen',
    language: 'Malay',
    level: 'Advanced',
    type: 'Listening',
    title: 'Ucapan Rasmi',
    description: 'Dengar ucapan rasmi dan fahami maksudnya.',
    questions: [
      { id: 'q37', type: 'Listening', question: 'Apakah tema ucapan?', options: ['Perpaduan kaum', 'Ekonomi negara', 'Pendidikan digital', 'Kesihatan awam'], correctAnswer: 'Perpaduan kaum', audioText: 'Kita mestilah mengekalkan semangat perpaduan demi keharmonian negara tercinta.' },
      { id: 'q37b', type: 'Listening', question: 'Apakah saranan penceramah?', options: ['Bekerja keras', 'Saling menghormati', 'Menabung wang', 'Belajar bersungguh-sungguh'], correctAnswer: 'Saling menghormati', audioText: 'Sikap saling menghormati antara satu sama lain adalah kunci kejayaan kita.' },
      { id: 'q37c', type: 'Listening', question: 'Apakah industri yang sedang berkembang?', options: ['Pelancongan', 'Teknologi maklumat', 'Pertanian', 'Perikanan'], correctAnswer: 'Teknologi maklumat', audioText: 'Industri teknologi maklumat sedang pesat berkembang di negara kita masa kini.' },
      { id: 'q37d', type: 'Listening', question: 'Apakah cabaran utama ekonomi?', options: ['Inflasi', 'Pengangguran', 'Kekurangan tenaga kerja', 'Kadar faedah tinggi'], correctAnswer: 'Inflasi', audioText: 'Cabaran utama ekonomi global sekarang adalah untuk mengawal kadar inflasi yang semakin meningkat.' },
      { id: 'q37e', type: 'Listening', question: 'Siapakah yang mendapat manfaat daripada dasar baharu ini?', options: ['Golongan belia', 'Warga emas', 'Kanak-kanak', 'Sektor swasta'], correctAnswer: 'Golongan belia', audioText: 'Dasar baharu ini diwujudkan khas untuk memperkasakan golongan belia dalam bidang keusahawanan.' },
      { id: 'q37f', type: 'Listening', question: 'Apakah fokus program kesihatan tersebut?', options: ['Pemakanan sihat', 'Senaman harian', 'Kesihatan mental', 'Vaksinasi'], correctAnswer: 'Kesihatan mental', audioText: 'Kita perlu memberi perhatian yang lebih serius terhadap isu kesihatan mental di tempat kerja.' },
      { id: 'q37g', type: 'Listening', question: 'Apakah yang perlu dilakukan untuk melestarikan alam sekitar?', options: ['Kitar semula', 'Pembakaran terbuka', 'Penebangan hutan', 'Penggunaan plastik'], correctAnswer: 'Kitar semula', audioText: 'Amalan kitar semula mestilah dijadikan budaya hidup untuk melestarikan alam sekitar kita.' },
      { id: 'q37h', type: 'Listening', question: 'Apakah peranan ibu bapa dalam pendidikan?', options: ['Memberi wang', 'Membeli buku', 'Memberi sokongan moral', 'Mencari sekolah'], correctAnswer: 'Memberi sokongan moral', audioText: 'Ibu bapa memainkan peranan penting dalam memberi sokongan moral kepada anak-anak yang menduduki peperiksaan.' },
      { id: 'q37i', type: 'Listening', question: 'Apakah kesan perubahan iklim?', options: ['Banjir besar', 'Pemanasan global', 'Kenaikan paras laut', 'Semua di atas'], correctAnswer: 'Semua di atas', audioText: 'Perubahan iklim membawa kesan buruk seperti pemanasan global dan kenaikan paras air laut yang membimbangkan.' },
      { id: 'q37j', type: 'Listening', question: 'Apakah matlamat pembangunan mampan?', options: ['Keuntungan jangka pendek', 'Keseimbangan ekonomi dan sosial', 'Pembinaan bangunan tinggi', 'Eksport bahan mentah'], correctAnswer: 'Keseimbangan ekonomi dan sosial', audioText: 'Matlamat pembangunan mampan adalah untuk mencapai keseimbangan antara pertumbuhan ekonomi dan kesejahteraan sosial.' },
    ]
  },
  {
    id: 'ms-adv-speak',
    language: 'Malay',
    level: 'Advanced',
    type: 'Speaking',
    title: 'Pidato',
    description: 'Sampaikan pidato ringkas.',
    questions: [
      { id: 'q38', type: 'Speaking', question: 'Sebut: "Kepentingan memelihara alam sekitar adalah tanggungjawab kita bersama."', sampleAnswer: 'Kepentingan memelihara alam sekitar adalah tanggungjawab kita bersama.' },
      { id: 'q38b', type: 'Speaking', question: 'Sebut: "Generasi muda adalah aset negara yang paling berharga."', sampleAnswer: 'Generasi muda adalah aset negara yang paling berharga.' },
      { id: 'q38c', type: 'Speaking', question: 'Sebut: "Inovasi dalam bidang sains pemangkin pertumbuhan ekonomi masa depan."', sampleAnswer: 'Inovasi dalam bidang sains pemangkin pertumbuhan ekonomi masa depan.' },
      { id: 'q38d', type: 'Speaking', question: 'Sebut: "Kesantunan berbahasa mencerminkan keperibadian sesuatu bangsa itu sendiri."', sampleAnswer: 'Kesantunan berbahasa mencerminkan keperibadian sesuatu bangsa itu sendiri.' },
      { id: 'q38e', type: 'Speaking', question: 'Sebut: "Perpaduan nasional adalah tunjang utama kestabilan dan keamanan negara."', sampleAnswer: 'Perpaduan nasional adalah tunjang utama kestabilan and keamanan negara.' },
      { id: 'q38f', type: 'Speaking', question: 'Sebut: "Teknologi digital memudahkan akses kepada maklumat tanpa sempadan."', sampleAnswer: 'Teknologi digital memudahkan akses kepada maklumat tanpa sempadan.' },
      { id: 'q38g', type: 'Speaking', question: 'Sebut: "Pendidikan sepanjang hayat menjamin kelestarian ilmu dalam masyarakat."', sampleAnswer: 'Pendidikan sepanjang hayat menjamin kelestarian ilmu dalam masyarakat.' },
      { id: 'q38h', type: 'Speaking', question: 'Sebut: "Keusahawanan sosial mampu menangani pelbagai isu kemasyarakatan hari ini."', sampleAnswer: 'Keusahawanan sosial mampu menangani pelbagai isu kemasyarakatan hari ini.' },
      { id: 'q38i', type: 'Speaking', question: 'Sebut: "Integriti dan akauntabiliti perlu diamalkan dalam setiap organisasi."', sampleAnswer: 'Integriti dan akauntabiliti perlu diamalkan dalam setiap organisasi.' },
      { id: 'q38j', type: 'Speaking', question: 'Sebut: "Keindahan seni sastera melambangkan ketinggian nilai budaya kita."', sampleAnswer: 'Keindahan seni sastera melambangkan ketinggian nilai budaya kita.' },
    ]
  },
  {
    id: 'ms-adv-write',
    language: 'Malay',
    level: 'Advanced',
    type: 'Writing',
    title: 'Karangan',
    description: 'Tulis karangan tentang isu semasa.',
    questions: [
      { id: 'q39', type: 'Writing', question: 'Tulis pendapat anda tentang kesan media sosial kepada remaja.', sampleAnswer: 'Media sosial mempunyai kesan positif dan negatif kepada perkembangan minda remaja masa kini.' },
      { id: 'q39b', type: 'Writing', question: 'Tulis pendapat anda tentang kepentingan gaya hidup sihat.', sampleAnswer: 'Gaya hidup sihat sangat penting untuk mengelakkan penyakit kronik di masa hadapan.' },
      { id: 'q39c', type: 'Writing', question: 'Bincangkan kesan penggunaan plastik sekali guna terhadap alam sekitar.', sampleAnswer: 'Penggunaan plastik sekali guna menyebabkan pencemaran laut yang serius dan menjejaskan hidupan akuatik.' },
      { id: 'q39d', type: 'Writing', question: 'Sejauh manakah pendidikan digital penting dalam sistem persekolahan sekarang?', sampleAnswer: 'Pendidikan digital sangat penting untuk menyediakan pelajar dengan kemahiran teknologi yang diperlukan dalam pasaran kerja global.' },
      { id: 'q39e', type: 'Writing', question: 'Tulis tentang peranan belia dalam mempromosikan perpaduan kaum.', sampleAnswer: 'Belia boleh mempromosikan perpaduan melalui aktiviti sukarelawan dan sukan yang melibatkan pelbagai kaum.' },
      { id: 'q39f', type: 'Writing', question: 'Berikan pandangan anda tentang cabaran keselamatan siber masa kini.', sampleAnswer: 'Keselamatan siber menjadi cabaran utama apabila lebih banyak data peribadi dikongsi secara dalam talian.' },
      { id: 'q39g', type: 'Writing', question: 'Huraikan kebaikan melancong di dalam negara sendiri.', sampleAnswer: 'Melancong di dalam negara dapat membantu meningkatkan ekonomi tempatan dan menghargai keindahan tanah air.' },
      { id: 'q39h', type: 'Writing', question: 'Bincangkan kepentingan memelihara warisan budaya tradisional.', sampleAnswer: 'Warisan budaya tradisional perlu dipelihara agar identiti bangsa tidak hilang ditelan zaman moden.' },
      { id: 'q39i', type: 'Writing', question: 'Adakah AI akan menggantikan peranan manusia di masa depan?', sampleAnswer: 'Walaupun AI boleh melakukan banyak tugas, nilai kemanusiaan dan empati masih tidak dapat digantikan sepenuhnya.' },
      { id: 'q39j', type: 'Writing', question: 'Bincangkan keberkesanan pembelajaran dalam talian berbanding secara fizikal.', sampleAnswer: 'Pembelajaran dalam talian menawarkan fleksibiliti, manakala pembelajaran fizikal membolehkan interaksi sosial yang lebih mendalam.' },
    ]
  },
  {
    id: 'ms-adv-comp',
    language: 'Malay',
    level: 'Advanced',
    type: 'Comprehension',
    title: 'Sastera Melayu',
    description: 'Baca petikan sastera dan fahami gaya bahasa.',
    questions: [
      { id: 'q40', type: 'Comprehension', question: 'Apakah maksud tersirat? "Laksana pohon yang tidak berbuah."', options: ['Sia-sia', 'Berguna', 'Cantik', 'Kuat'], correctAnswer: 'Sia-sia' },
      { id: 'q40b', type: 'Comprehension', question: 'Apakah peribahasa yang sesuai untuk orang yang rajin?', options: ['Seperti katak di bawah tempurung', 'Seperti lipas kudung', 'Seperti anjing dengan kucing', 'Como kera mendapat bunga'], correctAnswer: 'Seperti lipas kudung' },
      { id: 'q40c', type: 'Comprehension', question: 'Apakah maksud peribahasa "Mencari jalan"?', options: ['Berjalan-jalan', 'Berusaha menyelesaikan masalah', 'Sesat di jalan raya', 'Membina jalan baru'], correctAnswer: 'Berusaha menyelesaikan masalah' },
      { id: 'q40d', type: 'Comprehension', question: 'Berdasarkan ayat: "Budi yang baik akan dikenang selama-lamanya", apakah nilai murni yang ditekankan?', options: ['Keikhlasan', 'Keberanian', 'Kebijaksanaan', 'Kerajinan'], correctAnswer: 'Keikhlasan' },
      { id: 'q40e', type: 'Comprehension', question: 'Apakah maksud simpulan bahasa "Anak emas"?', options: ['Anak yang kaya', 'Anak yang sangat disayangi', 'Anak yang suka tidur', 'Anak yang pandai'], correctAnswer: 'Anak yang sangat disayangi' },
      { id: 'q40f', type: 'Comprehension', question: 'Apakah maksud peribahasa "Bagai aur dengan tebing"?', options: ['Saling bermusuhan', 'Saling membantu', 'Sangat sombong', 'Sangat malas'], correctAnswer: 'Saling membantu' },
      { id: 'q40g', type: 'Comprehension', question: 'Dalam ayat: "Dia bekerja siang malam untuk menyara keluarganya", apakah perwatakan tokoh?', options: ['Bertanggungjawab', 'Berdikari', 'Penyayang', 'Semua di atas'], correctAnswer: 'Semua di atas' },
      { id: 'q40h', type: 'Comprehension', question: 'Apakah maksud peribahasa "Sedia payung sebelum hujan"?', options: ['Membeli payung baru', 'Berwaspada sebelum ditimpa kesusahan', 'Berdiri di tengah hujan', 'Mencari tempat berteduh'], correctAnswer: 'Berwaspada sebelum ditimpa kesusahan' },
      { id: 'q40i', type: 'Comprehension', question: 'Apakah maksud simpulan bahasa "Makan hati"?', options: ['Suka makan hati ayam', 'Berasa sedih yang amat sangat', 'Selalu merasa lapar', 'Sangat gembira'], correctAnswer: 'Berasa sedih yang amat sangat' },
      { id: 'q40j', type: 'Comprehension', question: 'Apakah maksud peribahasa "Bulat air kerana pembetung, bulat kata kerana muafakat"?', options: ['Kebersihan air', 'Kepentingan bekerjasama dalam masyarakat', 'Bentuk air yang bulat', 'Selalu bercakap benar'], correctAnswer: 'Kepentingan bekerjasama dalam masyarakat' },
    ]
  },

  // ==========================================
  // CHINESE
  // ==========================================
  
  // BEGINNER
  {
    id: 'zh-beg-listen',
    language: 'Chinese',
    level: 'Beginner',
    type: 'Listening',
    title: '基础问候',
    description: '听常见的问候语并识别。',
    questions: [
      { id: 'q6', type: 'Listening', question: '你听到了什么？', options: ['你好', '再见', '谢谢', '对不起'], correctAnswer: '你好', audioText: '你好，很高兴认识你。' },
      { id: 'q6b', type: 'Listening', question: '你听到了什么？', options: ['早上好', '下午好', '晚上好', '晚安'], correctAnswer: '早上好', audioText: '大家早上好。' },
      { id: 'q6c', type: 'Listening', question: '你听到了什么？', options: ['谢谢', '不客气', '对不起', '没关系'], correctAnswer: '谢谢', audioText: '谢谢你的帮助。' },
      { id: 'q6d', type: 'Listening', question: '你听到了什么？', options: ['再见', '明天见', '等一下', '请进'], correctAnswer: '再见', audioText: '再见，祝你有个愉快的一天。' },
      { id: 'q6e', type: 'Listening', question: '你听到了什么？', options: ['多少钱？', '你在哪？', '你是谁？', '你好吗？'], correctAnswer: '你是谁？', audioText: '你是谁？我不认识你。' },
      { id: 'q6f', type: 'Listening', question: '你听到了什么？', options: ['好吃', '好喝', '好看', '好听'], correctAnswer: '好吃', audioText: '这个菜真的很好吃。' },
      { id: 'q6g', type: 'Listening', question: '你听到了什么？', options: ['红色', '蓝色', '黄色', '绿色'], correctAnswer: '红色', audioText: '我最喜欢的颜色是红色。' },
      { id: 'q6h', type: 'Listening', question: '你听到了什么？', options: ['医生', '老师', '学生', '工人'], correctAnswer: '老师', audioText: '我的妈妈是一名老师。' },
      { id: 'q6i', type: 'Listening', question: '你听到了什么？', options: ['北京', '上海', '广州', '深圳'], correctAnswer: '北京', audioText: '我下周要去北京出差。' },
      { id: 'q6j', type: 'Listening', question: '你听到了什么？', options: ['喝茶', '喝咖啡', '喝水', '喝酒'], correctAnswer: '喝咖啡', audioText: '你想要喝咖啡还是喝茶？' },
    ]
  },
  {
    id: 'zh-beg-speak',
    language: 'Chinese',
    level: 'Beginner',
    type: 'Speaking',
    title: '自我介绍',
    description: '练习说出你的名字和来自哪里。',
    questions: [
      { id: 'q50', type: 'Speaking', question: '说： “我叫小明，我来自北京。”', sampleAnswer: '我叫小明，我来自北京。', pinyin: 'wǒ jiào xiǎo míng, wǒ lái zì běi jīng.' },
      { id: 'q50b', type: 'Speaking', question: '说： “我喜欢吃米饭。”', sampleAnswer: '我喜欢吃米饭。', pinyin: 'wǒ xǐ huan chī mǐ fàn.' },
      { id: 'q50c', type: 'Speaking', question: '说： “我今年二十岁。”', sampleAnswer: '我今年二十岁。', pinyin: 'wǒ jīn nián èr shí suì.' },
      { id: 'q50d', type: 'Speaking', question: '说： “我的爱好是打篮球。”', sampleAnswer: '我的爱好是打篮球。', pinyin: 'wǒ de ài hào shì dǎ lán qiú.' },
      { id: 'q50e', type: 'Speaking', question: '说： “我有两个哥哥和一个姐姐。”', sampleAnswer: '我有两个哥哥和一个姐姐。', pinyin: 'wǒ yǒu liǎng gè gē ge hé yí gè jiě jie.' },
      { id: 'q50f', type: 'Speaking', question: '说： “今天的天气非常好。”', sampleAnswer: '今天的天气非常好。', pinyin: 'jīn tiān de tiān qì fēi cháng hǎo.' },
      { id: 'q50g', type: 'Speaking', question: '说： “很高兴能在学校见到你。”', sampleAnswer: '很高兴能在学校见到你。', pinyin: 'hěn gāo xìng néng zài xué xiào jiàn dào nǐ.' },
      { id: 'q50h', type: 'Speaking', question: '说： “我正在学习汉语。”', sampleAnswer: '我正在学习汉语。', pinyin: 'wǒ zhèng zài xué xí hàn yǔ.' },
      { id: 'q50i', type: 'Speaking', question: '说： “这里的食物很美味。”', sampleAnswer: '这里的食物很美味。', pinyin: 'zhè lǐ de shí wù hěn měi wèi.' },
      { id: 'q50j', type: 'Speaking', question: '说： “祝你有个愉快的一天。”', sampleAnswer: '祝你有个愉快的一天。', pinyin: 'zhù nǐ yǒu gè yú kuài de yì tiān.' },
    ]
  },
  {
    id: 'zh-beg-write',
    language: 'Chinese',
    level: 'Beginner',
    type: 'Writing',
    title: '简单汉字',
    description: '写出简单的汉字描述。',
    questions: [
      { id: 'q51', type: 'Writing', question: '写一个句子介绍你的家人。', sampleAnswer: '我家有三口人。' },
      { id: 'q51b', type: 'Writing', question: '写一个句子介绍你的爱好。', sampleAnswer: '我的爱好是看书。' },
      { id: 'q51c', type: 'Writing', question: '写一个句子描述现在的天气。', sampleAnswer: '今天天气很晴朗，没有云。' },
      { id: 'q51d', type: 'Writing', question: '写一个句子介绍你最喜欢的食物。', sampleAnswer: '我最喜欢吃妈妈做的红烧肉。' },
      { id: 'q51e', type: 'Writing', question: '写一个句子描述你的学校或工作单位。', sampleAnswer: '我的学校很大，有很多树木。' },
      { id: 'q51f', type: 'Writing', question: '写一个句子描述你最好的朋友。', sampleAnswer: '我最好的朋友叫张伟，他很阳光。' },
      { id: 'q51g', type: 'Writing', question: '写一个句子说说你周末通常做什么。', sampleAnswer: '周末我通常会和家人一起去公园。' },
      { id: 'q51h', type: 'Writing', question: '写一个句子描述此时此刻你的心情。', sampleAnswer: '我现在感到非常开心和兴奋。' },
      { id: 'q51i', type: 'Writing', question: '写一个句子介绍你喜欢的一种运动。', sampleAnswer: '我非常喜欢打乒乓球。' },
      { id: 'q51j', type: 'Writing', question: '写一个句子描述你最想去的城市。', sampleAnswer: '我未来最想去上海旅游。' },
    ]
  },
  {
    id: 'zh-beg-comp',
    language: 'Chinese',
    level: 'Beginner',
    type: 'Comprehension',
    title: '短文阅读',
    description: '阅读短文并回答问题。',
    questions: [
      { id: 'q52', type: 'Comprehension', question: '他在做什么？ “他在书房看书。”', options: ['吃饭', '看书', '睡觉', '跑步'], correctAnswer: '看书', pinyin: 'tā zài shū fáng kàn shū.' },
      { id: 'q52b', type: 'Comprehension', question: '车是什么颜色的？ “那辆红色的车很快。”', options: ['蓝色', '红色', '黄色', '绿色'], correctAnswer: '红色', pinyin: 'nà liàng hóng sè de chē hěn kuài.' },
      { id: 'q52c', type: 'Comprehension', question: '谁来了？ “一个高个子男人来到了家里。”', options: ['小孩', '高个子男人', '老太太', '猫'], correctAnswer: '高个子男人', pinyin: 'yí gè gāo gè zi nán rén lái dào le jiā lǐ.' },
      { id: 'q52d', type: 'Comprehension', question: '现在是几点？ “现在已经是晚上九点了。”', options: ['六点', '七点', '八点', '九点'], correctAnswer: '九点', pinyin: 'xiàn zài yǐ jīng shì wǎn shang jiǔ diǎn le.' },
      { id: 'q52e', type: 'Comprehension', question: '他在哪里买的苹果？ “我在超市买了一些新鲜的苹果。”', options: ['超级市场', '商场', '书店', '医院'], correctAnswer: '超级市场', pinyin: 'wǒ zài chāo shì mǎi le yì xiē xīn xiān de píng guǒ.' },
      { id: 'q52f', type: 'Comprehension', question: '天气怎么样？ “外面正下着鹅毛大雪。”', options: ['刮风', '下雨', '下雪', '天晴'], correctAnswer: '下雪', pinyin: 'wài mian zhèng xià zhe é máo dà xuě.' },
      { id: 'q52g', type: 'Comprehension', question: '桌子上有什么？ “桌子上放着一本厚厚的词典。”', options: ['笔记本', '电脑', '词典', '手机'], correctAnswer: '词典', pinyin: 'zhuō zi shang fàng zhe yì běn hòu hòu de cí diǎn.' },
      { id: 'q52h', type: 'Comprehension', question: '他在喝什么？ “他正在喝一杯热腾腾的绿茶。”', options: ['咖啡', '牛奶', '果汁', '绿茶'], correctAnswer: '绿茶', pinyin: 'tā zhèng zài hē yì bēi rè téng téng de lǜ chá.' },
      { id: 'q52i', type: 'Comprehension', question: '这是谁的手机？ “这是我哥哥刚买的新手机。”', options: ['我的', '妈妈的', '哥哥的', '姐姐的'], correctAnswer: '哥哥的', pinyin: 'zhè shì wǒ gē ge gāng mǎi de xīn shǒu jī.' },
      { id: 'q52j', type: 'Comprehension', question: '小猫在哪里？ “小猫正在沙发下面睡觉。”', options: ['沙发上面', '沙发下面', '桌子上面', '床上'], correctAnswer: '沙发下面', pinyin: 'xiǎo māo zhèng zài shā fā xià mian shuì jiào.' },
    ]
  },

  // INTERMEDIATE
  {
    id: 'zh-int-listen',
    language: 'Chinese',
    level: 'Intermediate',
    type: 'Listening',
    title: '购物对话',
    description: '听商场里的对话。',
    questions: [
      { id: 'q53', type: 'Listening', question: '这件衣服多少钱？', options: ['一百块', '两百块', '五十块', '八十块'], correctAnswer: '一百块', audioText: '这件衣服打折后是一百块钱。' },
      { id: 'q53b', type: 'Listening', question: '他在哪儿买的东西？', options: ['超市', '商场', '书店', '药店'], correctAnswer: '商场', audioText: '我昨天在商场买了很多东西。' },
      { id: 'q53c', type: 'Listening', question: '她明天要去哪里？', options: ['银行', '火车站', '机场', '图书馆'], correctAnswer: '机场', audioText: '我明天得早起去机场接我的朋友。' },
      { id: 'q53d', type: 'Listening', question: '他们打算什么时候吃饭？', options: ['十二点', '十二点半', '一点', '两点'], correctAnswer: '十二点半', audioText: '不如我们十二点半在餐厅门口见面吃饭吧。' },
      { id: 'q53e', type: 'Listening', question: '他为什么没去上班？', options: ['感冒了', '迟到了', '加班', '休假'], correctAnswer: '感冒了', audioText: '对不起，我今天有点感冒，不能去公司上班了。' },
      { id: 'q53f', type: 'Listening', question: '他觉得这本小说怎么样？', options: ['没意思', '很有趣', '太长了', '太难了'], correctAnswer: '很有趣', audioText: '这本小说写得非常有趣，推荐你也读一读。' },
      { id: 'q53g', type: 'Listening', question: '外面现在的天气如何？', options: ['晴天', '阴天', '下雨', '刮风'], correctAnswer: '下雨', audioText: '外面正下着雨呢，你出门记得带把伞。' },
      { id: 'q53h', type: 'Listening', question: '这个包裹寄往哪里？', options: ['北京', '上海', '广州', '成都'], correctAnswer: '上海', audioText: '请帮我把这个包裹寄到上海。' },
      { id: 'q53i', type: 'Listening', question: '他们在讨论什么？', options: ['考试', '旅游', '电影', '音乐'], correctAnswer: '电影', audioText: '你昨天晚上看的那个平衡宇宙电影怎么样？太震撼了！' },
      { id: 'q53j', type: 'Listening', question: '他学习汉语多久了？', options: ['三个月', '半年', '一年', '两年'], correctAnswer: '一年', audioText: '我已经学习汉语一年了，现在能进行基本的沟通。' },
    ]
  },
  {id: 'zh-int-speak',
    language: 'Chinese',
    level: 'Intermediate',
    type: 'Speaking',
    title: '谈论天气',
    description: '练习描述今天的天气。',
    questions: [
      { id: 'q54', type: 'Speaking', question: '说： “今天天气很好，阳光明媚，适合出去玩。”', sampleAnswer: '今天天气很好，阳光明媚，适合出去玩。', pinyin: 'jīn tiān tiān qì hěn hǎo, yáng guāng míng mèi, shì hé chū qù wán.' },
      { id: 'q54b', type: 'Speaking', question: '说： “明天可能会下雨，记得带伞。”', sampleAnswer: '明天可能会下雨，记得带伞。', pinyin: 'míng tiān kě néng huì xià yǔ, jì de dài sǎn.' },
      { id: 'q54c', type: 'Speaking', question: '说： “我最喜欢的运动是游泳和跑步。”', sampleAnswer: '我最喜欢的运动是游泳和跑步。', pinyin: 'wǒ zuì xǐ huan de yùn dòng shì yóu yǒng hé pǎo bù.' },
      { id: 'q54d', type: 'Speaking', question: '说： “请问，附近有可以换钱的地方吗？”', sampleAnswer: '请问，附近有可以换钱的地方吗？', pinyin: 'qǐng wèn, fù jìn yǒu kě yǐ huàn qián de dì fang ma?' },
      { id: 'q54e', type: 'Speaking', question: '说： “我打算下个月去上海旅游。”', sampleAnswer: '我打算下个月去上海旅游。', pinyin: 'wǒ dǎ suàn xià gè yuè qù shàng hǎi lǚ yóu.' },
      { id: 'q54f', type: 'Speaking', question: '说： “这道菜味道不错，但是有点太辣了。”', sampleAnswer: '这道菜味道不错，但是有点太辣了。', pinyin: 'zhè dào cài wèi dao bú cuò, dàn shì yǒu diǎn tài là le.' },
      { id: 'q54g', type: 'Speaking', question: '说： “我通常早起去公园锻炼身体。”', sampleAnswer: '我通常早起去公园锻炼身体。', pinyin: 'wǒ tōng cháng zǎo qǐ qù gōng yuán duàn liàn shēn tǐ.' },
      { id: 'q54h', type: 'Speaking', question: '说： “谢谢你邀请我参加你的生日派对。”', sampleAnswer: '谢谢你邀请我参加你的生日派对。', pinyin: 'xiè xie nǐ yāo qǐng wǒ cān jiā nǐ de shēng rì pài duì.' },
      { id: 'q54i', type: 'Speaking', question: '说： “我很期待下个星期的长假。”', sampleAnswer: '我很期待下个星期的长假。', pinyin: 'wǒ hěn qī dài xià gè xīng qī de cháng jià.' },
      { id: 'q54j', type: 'Speaking', question: '说： “对不起，我恐怕不能准时到达了。”', sampleAnswer: '对不起，我恐怕不能准时到达了。', pinyin: 'duì bu qǐ, wǒ kǒng pà bù néng zhǔn shí dào dá le.' },
    ]
  },
  {
    id: 'zh-int-write',
    language: 'Chinese',
    level: 'Intermediate',
    type: 'Writing',
    title: '写日记',
    description: '写一段简单的日记。',
    questions: [
      { id: 'q55', type: 'Writing', question: '写一段话描述你今天做了什么。', sampleAnswer: '今天我去了公园，看到很多漂亮的花。' },
      { id: 'q55b', type: 'Writing', question: '写一段话描述你的好朋友。', sampleAnswer: '我的好朋友叫小华，他很聪明也很友好。' },
      { id: 'q55c', type: 'Writing', question: '写一段话描述你最喜欢的电影。', sampleAnswer: '我最喜欢的电影是《星际穿越》，它的特效非常震撼。' },
      { id: 'q55d', type: 'Writing', question: '写一段话描述你的梦想职业。', sampleAnswer: '我梦想成为一名医生，因为我想帮助更多有需要的人。' },
      { id: 'q55e', type: 'Writing', question: '写一段话给你的老师表达感谢。', sampleAnswer: '老师，非常感谢这段时间以来您对我的耐心指导。' },
      { id: 'q55f', type: 'Writing', question: '写一段话描述你家乡的一处风景。', sampleAnswer: '我的家乡有一座美丽的湖泊，湖水在阳光下闪闪发光。' },
      { id: 'q55g', type: 'Writing', question: '写一段话描述一次难忘的旅行经历。', sampleAnswer: '去年夏天我去爬了长城，那里的风景让我至今记忆犹新。' },
      { id: 'q55h', type: 'Writing', question: '写一段话关于如何保持身体健康。', sampleAnswer: '保持健康需要均衡的饮食和规律的运动，早睡早起也很有帮助。' },
      { id: 'q55i', type: 'Writing', question: '写一段话描述你最喜欢的季节。', sampleAnswer: '我最喜欢秋天，因为秋高气爽，树叶变红的景色非常迷人。' },
      { id: 'q55j', type: 'Writing', question: '写一段话介绍你读过的一本好书。', sampleAnswer: '我最近读了《三体》，它展现了一个宏大的宇宙想象空间。' },
    ]
  },
  {
    id: 'zh-int-comp',
    language: 'Chinese',
    level: 'Intermediate',
    type: 'Comprehension',
    title: '故事阅读',
    description: '阅读成语故事并回答问题。',
    questions: [
      { id: 'q56', type: 'Comprehension', question: '这个故事告诉我们什么？', options: ['要努力', '要诚实', '要勇敢', '要聪明'], correctAnswer: '要努力' },
      { id: 'q56b', type: 'Comprehension', question: '谁是故事的主角？', options: ['一个小男孩', '一只老狼', '一个老农夫', '一只兔子'], correctAnswer: '一个老农夫' },
      { id: 'q56c', type: 'Comprehension', question: '故事发生在哪里？', options: ['在大森林里', '在一个小村庄', '在繁华的城市', '在茫茫大海上'], correctAnswer: '在一个小村庄' },
      { id: 'q56d', type: 'Comprehension', question: '农夫最后的收获是什么？', options: ['金子', '丰收的硕果', '一盒珠宝', '一句赞美'], correctAnswer: '丰收的硕果' },
      { id: 'q56e', type: 'Comprehension', question: '农夫为什么要把孩子叫来？', options: ['一起做游戏', '教他们种地的秘诀', '让他们去寻找虚构的财宝', '责备他们不努力'], correctAnswer: '让他们去寻找虚构的财宝' },
      { id: 'q56f', type: 'Comprehension', question: '孩子们最后明白财宝是指什么吗？', options: ['地下的金锭', '辛勤劳动换来的果实', '农夫的遗产', '一本藏宝图'], correctAnswer: '辛勤劳动换来的果实' },
      { id: 'q56g', type: 'Comprehension', question: '这个成语“守株待兔”中，那个人为什么没有收获？', options: ['他不够幸运', '他只知道等待而不努力', '兔子跑太快了', '树桩不够结实'], correctAnswer: '他只知道等待而不努力' },
      { id: 'q56h', type: 'Comprehension', question: '“画蛇添足”告诉我们什么道理？', options: ['做事情要多加点东西', '做多余的事反而会弄糟', '画蛇必须画脚', '要比赛画图'], correctAnswer: '做多余的事反而会弄糟' },
      { id: 'q56i', type: 'Comprehension', question: '“掩耳盗铃”中偷铃的人为什么要捂住自己的耳朵？', options: ['怕铃声太大', '以为自己听不见，别人也听不见', '想保护耳朵', '他在做游戏'], correctAnswer: '以为自己听不见，别人也听不见' },
      { id: 'q56j', type: 'Comprehension', question: '“守株待兔”的故事告诉我们：', options: ['只要等下去就有收获', '运气比努力更重要', '不能死守经验而不主动作', '兔子很笨'], correctAnswer: '不能死守经验而不主动作' },
    ]
  },
  {
    id: 'zh-adv-listen',
    language: 'Chinese',
    level: 'Advanced',
    type: 'Listening',
    title: '新闻广播',
    description: '听一段新闻并总结大意。',
    questions: [
      { id: 'q57', type: 'Listening', question: '新闻的主题是什么？', options: ['科技发展', '环境保护', '文化交流', '体育赛事'], correctAnswer: '科技发展', audioText: '近年来，人工智能技术在医疗领域取得了显著进展。' },
      { id: 'q57b', type: 'Listening', question: '新闻中提到了哪个领域？', options: ['教育', '医疗', '交通', '农业'], correctAnswer: '医疗', audioText: '人工智能正在改变我们的医疗诊断方式。' },
      { id: 'q57c', type: 'Listening', question: '国际空间站近期有何重大发现？', options: ['发现水源', '新的恒星', '完成补给', '实验新成果'], correctAnswer: '实验新成果', audioText: '国际空间站的宇航员近期在生物微重力实验中取得了突破性成果。' },
      { id: 'q57d', type: 'Listening', question: '当地政府为何决定新建公园？', options: ['增加绿化', '吸引投资', '居民抗议', '旧城改造'], correctAnswer: '增加绿化', audioText: '为了改善城市空气质量，当地政府决定在市中心开辟一处新的森林公园。' },
      { id: 'q57e', type: 'Listening', question: '这种新型电池的主要优势是什么？', options: ['更便宜', '充电更快', '体积更小', '更耐高温'], correctAnswer: '充电更快', audioText: '这种新型固态电池能在三分钟内充满电，极大缩短了充电时间。' },
      { id: 'q57f', type: 'Listening', question: '作者的新书将于什么时候出版？', options: ['下周', '下月', '明年', '年底'], correctAnswer: '下月', audioText: '知名科幻作家林冬的最新作品《量子幽灵》将于下月正式出版发行。' },
      { id: 'q57g', type: 'Listening', question: '该市的新交通法规旨在解决什么问题？', options: ['酒驾', '堵塞', '非机动车乱象', '自动驾驶'], correctAnswer: '非机动车乱象', audioText: '该市将于下周起实施新的非机动车管理条例，严厉打击闯红灯和逆行行为。' },
      { id: 'q57h', type: 'Listening', question: '新闻中提到了展会什么时候结束？', options: ['今天', '本周末', '下周二', '月底'], correctAnswer: '本周末', audioText: '本次中国国际博览会已吸引了数万名观众，展会将持续到本周末结束。' },
      { id: 'q57i', type: 'Listening', question: '运动员在这次比赛中打破了什么纪录？', options: ['世界纪录', '奥运会纪录', '个人最好成绩', '亚洲纪录'], correctAnswer: '世界纪录', audioText: '在男子一百米飞人大战中，中国选手以惊人的成绩打破了保持十年的世界纪录。' },
      { id: 'q57j', type: 'Listening', question: '当地社区举办这个活动是为了筹集什么？', options: ['书籍', '善款', '衣物', '食物'], correctAnswer: '善款', audioText: '为了帮助受灾地区的学校重建，社区今天组织了一场慈善马拉松活动来筹集善款。' },
    ]
  },
  {
    id: 'zh-adv-speak',
    language: 'Chinese',
    level: 'Advanced',
    type: 'Speaking',
    title: '发表演讲',
    description: '就一个社会话题发表演讲。',
    questions: [
      { id: 'q58', type: 'Speaking', question: '说： “保护环境是每个公民应尽的责任。”', sampleAnswer: '保护环境是每个公民应尽的责任。', pinyin: 'bǎo hù huán jìng shì měi gè gōng mín yīng jìn de zé rèn.' },
      { id: 'q58b', type: 'Speaking', question: '说： “科技进步为人类带来了前所未有的机遇。”', sampleAnswer: '科技进步为人类带来了前所未有的机遇。', pinyin: 'kē jì jìn bù wèi rén lèi dài lái le qián suǒ wèi yǒu de jī yù.' },
      { id: 'q58c', type: 'Speaking', question: '说： “我们要诚实守信，遵守社会公德。”', sampleAnswer: '我们要诚实守信，遵守社会公德。', pinyin: 'wǒ men yào chéng shí shǒu xìn, zūn shǒu shè huì gōng dé.' },
      { id: 'q58d', type: 'Speaking', question: '说： “青少年应该树立远大的理想和抱负。”', sampleAnswer: '青少年应该树立远大的理想和抱负。', pinyin: 'qīng shào nián yīng gāi shù lì yuǎn dà de lǐ xiǎng hé bào fù.' },
      { id: 'q58e', type: 'Speaking', question: '说： “创新是一个民族进步的灵魂。”', sampleAnswer: '创新是一个民族进步的灵魂。', pinyin: 'chuàng xīn shì yí gè mín zú jìn bù de líng hún.' },
      { id: 'q58f', type: 'Speaking', question: '说： “我们应该积极参与志愿者服务活动。”', sampleAnswer: '我们应该积极参与志愿者服务活动。', pinyin: 'wǒ men yīng gāi jī jí cān yù zhì yuàn zhě fú wù huó dòng.' },
      { id: 'q58g', type: 'Speaking', question: '说： “尊重他人就是尊重我们自己。”', sampleAnswer: '尊重他人就是尊重我们自己。', pinyin: 'zūn zhòng tā rén jiù shì zūn zhòng wǒ men zì jǐ.' },
      { id: 'q58h', type: 'Speaking', question: '说： “只有不断学习，才能跟上时代的步伐。”', sampleAnswer: '只有不断学习，才能跟上时代的步伐。', pinyin: 'zhǐ yǒu bú duàn xué xí, cái néng gēn shàng shí dài de bù fá.' },
      { id: 'q58i', type: 'Speaking', question: '说： “勤俭节约是中华民族的传统美德。”', sampleAnswer: '勤俭节约是中华民族的传统美德。', pinyin: 'qín jiǎn jié yuē shì zhōng huá mín zú de chuán tǒng měi dé.' },
      { id: 'q58j', type: 'Speaking', question: '说： “团结就是力量，这在任何时候都是真理。”', sampleAnswer: '团结就是力量，这在任何时候都是真理。', pinyin: 'tuán jié jiù shì lì liàng, zhè zài rèn hé shí hou dōu shì zhēn lǐ.' },
    ]
  },
  {
    id: 'zh-adv-write',
    language: 'Chinese',
    level: 'Advanced',
    type: 'Writing',
    title: '议论文',
    description: '写一篇关于社会现象的文章。',
    questions: [
      { id: 'q59', type: 'Writing', question: '写一段话讨论远程办公的优缺点。', sampleAnswer: '远程办公虽然提高了灵活性，但也可能导致沟通不畅。' },
      { id: 'q59b', type: 'Writing', question: '写一段话讨论城市化对环境的影响。', sampleAnswer: '城市化进程加快了经济发展，但也带来了环境污染问题。' },
      { id: 'q59c', type: 'Writing', question: '写一段话论述教育在减缓贫困中的作用。', sampleAnswer: '教育为个人提供了掌握技能的机会，是打破跨代贫困循环的关键。' },
      { id: 'q59d', type: 'Writing', question: '写一段话分析社交媒体对现代人际关系的影响。', sampleAnswer: '社交媒体拉近了地理上的距离，但在某种程度上也淡化了面对面的真实交流。' },
      { id: 'q59e', type: 'Writing', question: '写一段话谈谈你对人工智能未来发展的看法。', sampleAnswer: '人工智能将极大提高生产力，但我们也需警惕其可能带来的伦理风险。' },
      { id: 'q59f', type: 'Writing', question: '写一段话关于如何平衡工作与生活。', sampleAnswer: '合理的计划和坚定的边界感是实现工作与生活平衡的基石。' },
      { id: 'q59g', type: 'Writing', question: '写一段话探讨全球化背景下文化保护的重要性。', sampleAnswer: '在全球化的浪潮中，保护本土文化的多样性对于维护民族身份至关重要。' },
      { id: 'q59h', type: 'Writing', question: '写一段话论证终身学习在当今职场中的必要性。', sampleAnswer: '随着技术的快速迭代，终身学习已成为职场人士保持竞争力的核心手段。' },
      { id: 'q59i', type: 'Writing', question: '写一段话关于心理健康对城市居民的重要性。', sampleAnswer: '在快节奏的城市生活中，关注心理健康与关注生理健康同样重要。' },
      { id: 'q59j', type: 'Writing', question: '写一段话讨论可再生能源在未来的地位。', sampleAnswer: '为了实现可持续发展，可再生能源必然会取代传统化石燃料的主导地位。' },
    ]
  },
  {
    id: 'zh-adv-comp',
    language: 'Chinese',
    level: 'Advanced',
    type: 'Comprehension',
    title: '古诗词赏析',
    description: '阅读古诗并分析意境。',
    questions: [
      { id: 'q60', type: 'Comprehension', question: '阅读李白的《静夜思》：“床前明月光，疑是地上霜。举头望明月，低头思故乡。” 请问这首诗表达了作者怎样的情感？', options: ['思乡', '喜悦', '愤怒', '忧愁'], correctAnswer: '思乡', explanation: '《静夜思》是唐代诗人李白的作品，表达了诗人在寂静的夜晚，看到明月后引发的深切思乡之情。' },
      { id: 'q60b', type: 'Comprehension', question: '在《静夜思》中，诗中提到的 "明月" 象征着什么？', options: ['团圆', '孤独', '希望', '寒冷'], correctAnswer: '团圆', explanation: '在中国传统文化中，明月常被赋予团圆的意涵。诗人见月思乡，正是因为月圆象征着人也应团圆。' },
      { id: 'q60c', type: 'Comprehension', question: '阅读孟浩然的《春晓》：“春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。” 诗中描述的是哪个季节的早晨？', options: ['春天', '夏天', '秋天', '冬天'], correctAnswer: '春天', explanation: '《春晓》描绘的是春天早晨的景象，从标题“春晓”以及“啼鸟”、“花落”等意象可见。' },
      { id: 'q60d', type: 'Comprehension', question: '在《春晓》中，“处处闻啼鸟”的“闻”字是什么意思？', options: ['听见', '闻到(气味)', '新闻', '名字'], correctAnswer: '听见', explanation: '在古汉语中，“闻”通常指听见声音，而非现代汉语中常用的嗅觉含义。' },
      { id: 'q60e', type: 'Comprehension', question: '阅读王之涣的《登鹳雀楼》：“白日依山尽，黄河入海流。欲穷千里目，更上一层楼。” 这首诗告诉我们要怎样才能看得更远？', options: ['登得更高', '跑得更快', '睡得更多', '吃得更饱'], correctAnswer: '登得更高', explanation: '“欲穷千里目，更上一层楼”是千古名句，寓意只有站得更高，才能看得更远，比喻积极向上的进取精神。' },
      { id: 'q60f', type: 'Comprehension', question: '在《登鹳雀楼》中，“山”指的是什么样的山？', options: ['落日方向的山', '早晨的山', '海边的山', '花园里的假山'], correctAnswer: '落日方向的山', explanation: '“白日依山尽”描写的是夕阳西下的景象，因此山是指落日方向的山。' },
      { id: 'q60g', type: 'Comprehension', question: '阅读李白的《望庐山瀑布》：“日照香炉生紫烟，遥看瀑布挂前川。飞流直下三千尺，疑是银河落九天。” 诗中的“三千尺”主要使用了哪种修辞手法？', options: ['夸张', '比喻', '拟人', '对偶'], correctAnswer: '夸张', explanation: '“三千尺”极言瀑布之长，这是一种明显的夸张手法，用以增强诗歌的艺术感染力。' },
      { id: 'q60h', type: 'Comprehension', question: '在《望庐山瀑布》中，“飞流直下”描写的是什么？', options: ['瀑布', '河流', '下雨', '流星'], correctAnswer: '瀑布', explanation: '“飞流直下”生动地描绘了庐山瀑布从高处奔涌而下的壮观场景。' },
      { id: 'q60i', type: 'Comprehension', question: '阅读柳宗元的《江雪》：“千山鸟飞绝，万径人踪灭。孤舟蓑笠翁，独钓寒江雪。” 这首诗描绘了一种什么样的意境？', options: ['孤独清高', '热闹繁华', '春意盎然', '万马奔腾'], correctAnswer: '孤独清高', explanation: '《江雪》通过描写寂静寒冷的江面和孤独的老翁，表达了诗人孤傲、高洁、不畏环境艰辛的品格。' },
      { id: 'q60j', type: 'Comprehension', question: '在《江雪》中，“蓑笠翁”指的是什么样的人？', options: ['穿着雨衣斗笠的老人', '骑马的将军', '跳舞的青年', '正在划船的孩子'], correctAnswer: '穿着雨衣斗笠的老人', explanation: '“蓑”指蓑衣，“笠”指斗笠，都是古代农民或渔民防雨用的工具，“蓑笠翁”即穿着这些工具垂钓的老人。' },
    ]
  },
  {
    
    id: 'en-beg-vocab',
    language: 'English',
    level: 'Beginner',
    type: 'Vocabulary',
    title: 'Essential Verbs',
    description: 'Learn and review common English verbs.',
    questions: [
      { id: 'v1', type: 'Vocabulary', question: 'Which word means "to consume food"?', options: ['Eat', 'Drink', 'Sleep', 'Walk'], correctAnswer: 'Eat' },
      { id: 'v2', type: 'Vocabulary', question: 'Which word means "to consume liquid"?', options: ['Eat', 'Drink', 'Run', 'Sit'], correctAnswer: 'Drink' },
      { id: 'v3', type: 'Vocabulary', question: 'Which word means "to rest your body at night"?', options: ['Sleep', 'Wake', 'Wash', 'Cook'], correctAnswer: 'Sleep' },
      { id: 'v4_en', type: 'Vocabulary', question: 'Which word means "to move your legs quickly to get somewhere"?', options: ['Run', 'Stand', 'Hop', 'Dance'], correctAnswer: 'Run' },
      { id: 'v5_en', type: 'Vocabulary', question: 'Which word means "to speak with your voice"?', options: ['Talk', 'Blink', 'Nod', 'Clap'], correctAnswer: 'Talk' },
      { id: 'v6_en', type: 'Vocabulary', question: 'Which word means "to use your eyes to see things"?', options: ['Look', 'Listen', 'Smell', 'Taste'], correctAnswer: 'Look' },
      { id: 'v7_en', type: 'Vocabulary', question: 'Which word means "to create something with a pen on paper"?', options: ['Write', 'Read', 'Cut', 'Glue'], correctAnswer: 'Write' },
      { id: 'v8_en', type: 'Vocabulary', question: 'Which word means "to look at words in a book"?', options: ['Read', 'Paint', 'Sing', 'Jump'], correctAnswer: 'Read' },
      { id: 'v9_en', type: 'Vocabulary', question: 'Which word means "to give your attention to sounds"?', options: ['Listen', 'Watch', 'Touch', 'Feel'], correctAnswer: 'Listen' },
      { id: 'v10_en', type: 'Vocabulary', question: 'Which word means "to prepare food by heating it"?', options: ['Cook', 'Clean', 'Bake', 'Fry'], correctAnswer: 'Cook' },
    ]
  },
  {
    id: 'en-beg-grammar',
    language: 'English',
    level: 'Beginner',
    type: 'Grammar',
    title: 'To Be Verb',
    description: 'Practice using am, is, are.',
    questions: [
      { id: 'g1', type: 'Grammar', question: 'I ___ a student.', options: ['am', 'is', 'are'], correctAnswer: 'am' },
      { id: 'g2', type: 'Grammar', question: 'She ___ happy.', options: ['am', 'is', 'are'], correctAnswer: 'is' },
      { id: 'g3', type: 'Grammar', question: 'They ___ playing.', options: ['am', 'is', 'are'], correctAnswer: 'are' },
      { id: 'g4_en', type: 'Grammar', question: 'We ___ friends.', options: ['am', 'is', 'are'], correctAnswer: 'are' },
      { id: 'g5_en', type: 'Grammar', question: 'He ___ a doctor.', options: ['am', 'is', 'are'], correctAnswer: 'is' },
      { id: 'g6_en', type: 'Grammar', question: 'It ___ a beautiful day.', options: ['am', 'is', 'are'], correctAnswer: 'is' },
      { id: 'g7_en', type: 'Grammar', question: 'You ___ very kind.', options: ['am', 'is', 'are'], correctAnswer: 'are' },
      { id: 'g8_en', type: 'Grammar', question: 'The books ___ on the shelf.', options: ['is', 'are', 'am'], correctAnswer: 'are' },
      { id: 'g9_en', type: 'Grammar', question: 'My brother ___ at home.', options: ['is', 'are', 'am'], correctAnswer: 'is' },
      { id: 'g10_en', type: 'Grammar', question: 'The birds ___ singing.', options: ['is', 'are', 'am'], correctAnswer: 'are' },
    ]
  },
  {
    id: 'ms-beg-vocab',
    language: 'Malay',
    level: 'Beginner',
    type: 'Vocabulary',
    title: 'Perkataan Asas',
    description: 'Ketahui perkataan asas dalam Bahasa Melayu.',
    questions: [
      { id: 'v4', type: 'Vocabulary', question: 'Apakah maksud "Buku"?', options: ['Book', 'Table', 'Chair', 'Pen'], correctAnswer: 'Book' },
      { id: 'v5', type: 'Vocabulary', question: 'Apakah maksud "Tangan"?', options: ['Hand', 'Foot', 'Head', 'Eye'], correctAnswer: 'Hand' },
      { id: 'v11_ms', type: 'Vocabulary', question: 'Apakah maksud "Rumah"?', options: ['House', 'School', 'Office', 'Park'], correctAnswer: 'House' },
      { id: 'v12_ms', type: 'Vocabulary', question: 'Apakah maksud "Makan"?', options: ['Eat', 'Drink', 'Run', 'Sleep'], correctAnswer: 'Eat' },
      { id: 'v13_ms', type: 'Vocabulary', question: 'Apakah maksud "Minum"?', options: ['Eat', 'Drink', 'Run', 'Sleep'], correctAnswer: 'Drink' },
      { id: 'v14_ms', type: 'Vocabulary', question: 'Apakah maksud "Jalan"?', options: ['Road', 'Tree', 'River', 'Bird'], correctAnswer: 'Road' },
      { id: 'v15_ms', type: 'Vocabulary', question: 'Apakah maksud "Air"?', options: ['Water', 'Fire', 'Wind', 'Earth'], correctAnswer: 'Water' },
      { id: 'v16_ms', type: 'Vocabulary', question: 'Apakah maksud "Baju"?', options: ['Shirt', 'Pants', 'Shoes', 'Hat'], correctAnswer: 'Shirt' },
      { id: 'v17_ms', type: 'Vocabulary', question: 'Apakah maksud "Kaki"?', options: ['Leg', 'Arm', 'Eye', 'Ear'], correctAnswer: 'Leg' },
      { id: 'v18_ms', type: 'Vocabulary', question: 'Apakah maksud "Mata"?', options: ['Eye', 'Ear', 'Nose', 'Mouth'], correctAnswer: 'Eye' },
    ]
  },
  {
    id: 'ms-beg-grammar',
    language: 'Malay',
    level: 'Beginner',
    type: 'Grammar',
    title: 'Kata Ganti Nama',
    description: 'Latihan menggunakan saya, kamu, dia.',
    questions: [
      { id: 'g4', type: 'Grammar', question: '___ mahu makan.', options: ['Saya', 'Itu', 'Sana'], correctAnswer: 'Saya' },
      { id: 'g11_ms', type: 'Grammar', question: '___ sedang membaca buku.', options: ['Dia', 'Ini', 'Sini'], correctAnswer: 'Dia' },
      { id: 'g12_ms', type: 'Grammar', question: '___ suka bermain bola.', options: ['Kamu', 'Itu', 'Situ'], correctAnswer: 'Kamu' },
      { id: 'g13_ms', type: 'Grammar', question: '___ pergi ke sekolah.', options: ['Kami', 'Inilah', 'Begitu'], correctAnswer: 'Kami' },
      { id: 'g14_ms', type: 'Grammar', question: '___ mahu tidur sekarang.', options: ['Mereka', 'Demikian', 'Manakala'], correctAnswer: 'Mereka' },
      { id: 'g15_ms', type: 'Grammar', question: '___ adakah nama anda?', options: ['Siapa', 'Apa', 'Mana'], correctAnswer: 'Siapa' },
      { id: 'g16_ms', type: 'Grammar', question: '___kah harga baju ini?', options: ['Berapa', 'Mengapa', 'Bagaimana'], correctAnswer: 'Berapa' },
      { id: 'g17_ms', type: 'Grammar', question: '___kah anda tinggal?', options: ['Di mana', 'Ke mana', 'Dari mana'], correctAnswer: 'Di mana' },
      { id: 'g18_ms', type: 'Grammar', question: '___kah anda menangis?', options: ['Mengapa', 'Bilakah', 'Adakah'], correctAnswer: 'Mengapa' },
      { id: 'g19_ms', type: 'Grammar', question: '___kah berita itu benar?', options: ['Adakah', 'Berakah', 'Siapakah'], correctAnswer: 'Adakah' },
    ]
  },
  {
    id: 'zh-beg-vocab',
    language: 'Chinese',
    level: 'Beginner',
    type: 'Vocabulary',
    title: '常用动词',
    description: '学习常用的中文动词。',
    questions: [
      { id: 'v6', type: 'Vocabulary', question: '"看" 的意思是什么？', options: ['To look', 'To listen', 'To speak', 'To write'], correctAnswer: 'To look', pinyin: 'kàn' },
      { id: 'v7', type: 'Vocabulary', question: '"听" 的意思是什么？', options: ['To look', 'To listen', 'To speak', 'To write'], correctAnswer: 'To listen', pinyin: 'tīng' },
      { id: 'v19_zh', type: 'Vocabulary', question: '"说" 的意思是什么？', options: ['To speak', 'To eat', 'To walk', 'To play'], correctAnswer: 'To speak', pinyin: 'shuō' },
      { id: 'v20_zh', type: 'Vocabulary', question: '"写" 的意思是什么？', options: ['To write', 'To read', 'To draw', 'To cut'], correctAnswer: 'To write', pinyin: 'xiě' },
      { id: 'v21_zh', type: 'Vocabulary', question: '"吃" 的意思是什么？', options: ['To eat', 'To drink', 'To sleep', 'To run'], correctAnswer: 'To eat', pinyin: 'chī' },
      { id: 'v22_zh', type: 'Vocabulary', question: '"喝" 的意思是什么？', options: ['To drink', 'To jump', 'To sit', 'To stand'], correctAnswer: 'To drink', pinyin: 'hē' },
      { id: 'v23_zh', type: 'Vocabulary', question: '"走" 的意思是什么？', options: ['To walk', 'To fly', 'To swim', 'To sing'], correctAnswer: 'To walk', pinyin: 'zǒu' },
      { id: 'v24_zh', type: 'Vocabulary', question: '"跑" 的意思是什么？', options: ['To run', 'To climb', 'To hide', 'To open'], correctAnswer: 'To run', pinyin: 'pǎo' },
      { id: 'v25_zh', type: 'Vocabulary', question: '"买" 的意思是什么？', options: ['To buy', 'To sell', 'To give', 'To take'], correctAnswer: 'To buy', pinyin: 'mǎi' },
      { id: 'v26_zh', type: 'Vocabulary', question: '"卖" 的意思是什么？', options: ['To sell', 'To buy', 'To fix', 'To clean'], correctAnswer: 'To sell', pinyin: 'mài' },
    ]
  },
  {
    id: 'zh-beg-grammar',
    language: 'Chinese',
    level: 'Beginner',
    type: 'Grammar',
    title: '基础句型',
    description: '学习 "是" 字句。',
    questions: [
      { id: 'g5', type: 'Grammar', question: '我___老师。', options: ['是', '有', '在'], correctAnswer: '是', pinyin: 'wǒ ___ lǎo shī.' },
      { id: 'g20_zh', type: 'Grammar', question: '他___医生。', options: ['是', '有', '在'], correctAnswer: '是', pinyin: 'tā ___ yī shēng.' },
      { id: 'g21_zh', type: 'Grammar', question: '他们___学生。', options: ['是', '有', '在'], correctAnswer: '是', pinyin: 'tā men ___ xué sheng.' },
      { id: 'g22_zh', type: 'Grammar', question: '今天___星期一。', options: ['是', '有', '在'], correctAnswer: '是', pinyin: 'jīn tiān ___ xīng qī yī.' },
      { id: 'g23_zh', type: 'Grammar', question: '苹果___红色的。', options: ['是', '有', '在'], correctAnswer: '是', pinyin: 'píng guǒ ___ hóng sè de.' },
      { id: 'g24_zh', type: 'Grammar', question: '我___一个苹果。', options: ['有', '是', '在'], correctAnswer: '有', pinyin: 'wǒ ___ yí gè píng guǒ.' },
      { id: 'g25_zh', type: 'Grammar', question: '他___两本书。', options: ['有', '是', '在'], correctAnswer: '有', pinyin: 'tā ___ liǎng běn shū.' },
      { id: 'g26_zh', type: 'Grammar', question: '老师___教室里。', options: ['在', '是', '有'], correctAnswer: '在', pinyin: 'lǎo shī ___ jiào shì lǐ.' },
      { id: 'g27_zh', type: 'Grammar', question: '妈妈___厨房。', options: ['在', '是', '有'], correctAnswer: '在', pinyin: 'mā ma ___ chú fáng.' },
      { id: 'g28_zh', type: 'Grammar', question: '书___桌子上。', options: ['在', '是', '有'], correctAnswer: '在', pinyin: 'shū ___ zhuō zi shang.' },
    ]
  }
];
